export class vw_NWC_ContractTermsDTO {
      ID: number;
      Code: string;
      ContractTermName: string;
      Description: string;
      TermsCategoryID: number;
      ContractID: number;
      StationID: string;
      stationName: string;
      Category: string;
      stationCode: string;
      ContractTermCode: string;
      TotalValue: number;
      TotalValueUnitId: number;
      TotalValueUnitName: string;

}