//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.BLL.BlacklistServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nwc.com.sa/ws/echannelCheckAcctPerInBlackList", ConfigurationName="BlacklistServiceRef.CheckPersonInBlackListPortType")]
    public interface CheckPersonInBlackListPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckPersonInBlackListExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteResponse CheckPersonInBlackListExecute(NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="CheckPersonInBlackListExecute", ReplyAction="*")]
        System.Threading.Tasks.Task<NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteResponse> CheckPersonInBlackListExecuteAsync(NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eChannelService.nwc.com.sa")]
    public enum cisDivison {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        RCBU,
        
        /// <remarks/>
        JCBU,
        
        /// <remarks/>
        TCBU,
        
        /// <remarks/>
        MCBU,
        
        /// <remarks/>
        JZBU,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        RI,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        TB,
        
        /// <remarks/>
        RC,
        
        /// <remarks/>
        JC,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        QS,
        
        /// <remarks/>
        HS,
        
        /// <remarks/>
        HA,
        
        /// <remarks/>
        JF,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        NJ,
        
        /// <remarks/>
        JZ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList")]
    public enum CheckPersonInBlackListRequestSourceApplication {
        
        /// <remarks/>
        EBRANCH,
        
        /// <remarks/>
        MOBAPP,
        
        /// <remarks/>
        IVR,
        
        /// <remarks/>
        NOKHBA,
        
        /// <remarks/>
        TMS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList")]
    public partial class CheckPersonInBlackListResponseResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nidNumberField;
        
        private string acctIdField;
        
        private string meterStatusField;
        
        private string meterLockReasonField;
        
        private string customerClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nidNumber {
            get {
                return this.nidNumberField;
            }
            set {
                this.nidNumberField = value;
                this.RaisePropertyChanged("nidNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string acctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
                this.RaisePropertyChanged("acctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string meterStatus {
            get {
                return this.meterStatusField;
            }
            set {
                this.meterStatusField = value;
                this.RaisePropertyChanged("meterStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string meterLockReason {
            get {
                return this.meterLockReasonField;
            }
            set {
                this.meterLockReasonField = value;
                this.RaisePropertyChanged("meterLockReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customerClass {
            get {
                return this.customerClassField;
            }
            set {
                this.customerClassField = value;
                this.RaisePropertyChanged("customerClass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckPersonInBlackListRequest", WrapperNamespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", IsWrapped=true)]
    public partial class CheckPersonInBlackListExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=0)]
        public string transactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=1)]
        public NWC.BLL.BlacklistServiceRef.cisDivison cisDivison;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=2)]
        public string nidNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=3)]
        public string accountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=4)]
        public NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListRequestSourceApplication sourceApplication;
        
        public CheckPersonInBlackListExecuteRequest() {
        }
        
        public CheckPersonInBlackListExecuteRequest(string transactionId, NWC.BLL.BlacklistServiceRef.cisDivison cisDivison, string nidNumber, string accountId, NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListRequestSourceApplication sourceApplication) {
            this.transactionId = transactionId;
            this.cisDivison = cisDivison;
            this.nidNumber = nidNumber;
            this.accountId = accountId;
            this.sourceApplication = sourceApplication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckPersonInBlackListResponse", WrapperNamespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", IsWrapped=true)]
    public partial class CheckPersonInBlackListExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sourceApplication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=3)]
        public string responseCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=4)]
        public string responseDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=5)]
        public string errorCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=6)]
        public string errorDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=7)]
        public decimal rowcount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nwc.com.sa/xmlns/echannelCheckAcctPerInBlackList", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("results")]
        public NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListResponseResults[] results;
        
        public CheckPersonInBlackListExecuteResponse() {
        }
        
        public CheckPersonInBlackListExecuteResponse(string transactionId, string sourceApplication, string status, string responseCode, string responseDescription, string errorCode, string errorDescription, decimal rowcount, NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListResponseResults[] results) {
            this.transactionId = transactionId;
            this.sourceApplication = sourceApplication;
            this.status = status;
            this.responseCode = responseCode;
            this.responseDescription = responseDescription;
            this.errorCode = errorCode;
            this.errorDescription = errorDescription;
            this.rowcount = rowcount;
            this.results = results;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckPersonInBlackListPortTypeChannel : NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckPersonInBlackListPortTypeClient : System.ServiceModel.ClientBase<NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListPortType>, NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListPortType {
        
        public CheckPersonInBlackListPortTypeClient() {
        }
        
        public CheckPersonInBlackListPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckPersonInBlackListPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckPersonInBlackListPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckPersonInBlackListPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteResponse NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListPortType.CheckPersonInBlackListExecute(NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest request) {
            return base.Channel.CheckPersonInBlackListExecute(request);
        }
        
        public string CheckPersonInBlackListExecute(ref string transactionId, NWC.BLL.BlacklistServiceRef.cisDivison cisDivison, string nidNumber, string accountId, NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListRequestSourceApplication sourceApplication, out string status, out string responseCode, out string responseDescription, out string errorCode, out string errorDescription, out decimal rowcount, out NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListResponseResults[] results) {
            NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest inValue = new NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest();
            inValue.transactionId = transactionId;
            inValue.cisDivison = cisDivison;
            inValue.nidNumber = nidNumber;
            inValue.accountId = accountId;
            inValue.sourceApplication = sourceApplication;
            NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteResponse retVal = ((NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListPortType)(this)).CheckPersonInBlackListExecute(inValue);
            transactionId = retVal.transactionId;
            status = retVal.status;
            responseCode = retVal.responseCode;
            responseDescription = retVal.responseDescription;
            errorCode = retVal.errorCode;
            errorDescription = retVal.errorDescription;
            rowcount = retVal.rowcount;
            results = retVal.results;
            return retVal.sourceApplication;
        }
        
        public System.Threading.Tasks.Task<NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteResponse> CheckPersonInBlackListExecuteAsync(NWC.BLL.BlacklistServiceRef.CheckPersonInBlackListExecuteRequest request) {
            return base.Channel.CheckPersonInBlackListExecuteAsync(request);
        }
    }
}
