//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromCCBToNWC.API.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ITanker")]
    public interface ITanker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITanker/GetAvailableTankerSizes", ReplyAction="http://tempuri.org/ITanker/GetAvailableTankerSizesResponse")]
        NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Output GetAvailableTankerSizes(NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Schema schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITanker/GetAvailableTankerSizes", ReplyAction="http://tempuri.org/ITanker/GetAvailableTankerSizesResponse")]
        System.Threading.Tasks.Task<NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Output> GetAvailableTankerSizesAsync(NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Schema schema);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITankerChannel : FromCCBToNWC.API.ServiceReference2.ITanker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TankerClient : System.ServiceModel.ClientBase<FromCCBToNWC.API.ServiceReference2.ITanker>, FromCCBToNWC.API.ServiceReference2.ITanker {
        
        public TankerClient() {
        }
        
        public TankerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TankerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TankerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TankerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Output GetAvailableTankerSizes(NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Schema schema) {
            return base.Channel.GetAvailableTankerSizes(schema);
        }
        
        public System.Threading.Tasks.Task<NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Output> GetAvailableTankerSizesAsync(NWC_CCB_Integration.DTO.Models.AvailableTankerSize.Schema schema) {
            return base.Channel.GetAvailableTankerSizesAsync(schema);
        }
    }
}
