//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromCCBToNWC.API.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWorkOrder")]
    public interface IWorkOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/CreateWorkOrder", ReplyAction="http://tempuri.org/IWorkOrder/CreateWorkOrderResponse")]
        System.Xml.Linq.XElement CreateWorkOrder(System.Xml.Linq.XElement requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/CreateWorkOrder", ReplyAction="http://tempuri.org/IWorkOrder/CreateWorkOrderResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> CreateWorkOrderAsync(System.Xml.Linq.XElement requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/CreateWorkOrder2", ReplyAction="http://tempuri.org/IWorkOrder/CreateWorkOrder2Response")]
        System.Xml.Linq.XElement CreateWorkOrder2(NWC_CCB_Integration.DTO.Output.WorkOrderResponse requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/CreateWorkOrder2", ReplyAction="http://tempuri.org/IWorkOrder/CreateWorkOrder2Response")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> CreateWorkOrder2Async(NWC_CCB_Integration.DTO.Output.WorkOrderResponse requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/UpdateWorkOrder", ReplyAction="http://tempuri.org/IWorkOrder/UpdateWorkOrderResponse")]
        System.Xml.Linq.XElement UpdateWorkOrder(System.Xml.Linq.XElement requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrder/UpdateWorkOrder", ReplyAction="http://tempuri.org/IWorkOrder/UpdateWorkOrderResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> UpdateWorkOrderAsync(System.Xml.Linq.XElement requestXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkOrderChannel : FromCCBToNWC.API.ServiceReference1.IWorkOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkOrderClient : System.ServiceModel.ClientBase<FromCCBToNWC.API.ServiceReference1.IWorkOrder>, FromCCBToNWC.API.ServiceReference1.IWorkOrder {
        
        public WorkOrderClient() {
        }
        
        public WorkOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement CreateWorkOrder(System.Xml.Linq.XElement requestXml) {
            return base.Channel.CreateWorkOrder(requestXml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> CreateWorkOrderAsync(System.Xml.Linq.XElement requestXml) {
            return base.Channel.CreateWorkOrderAsync(requestXml);
        }
        
        public System.Xml.Linq.XElement CreateWorkOrder2(NWC_CCB_Integration.DTO.Output.WorkOrderResponse requestXml) {
            return base.Channel.CreateWorkOrder2(requestXml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> CreateWorkOrder2Async(NWC_CCB_Integration.DTO.Output.WorkOrderResponse requestXml) {
            return base.Channel.CreateWorkOrder2Async(requestXml);
        }
        
        public System.Xml.Linq.XElement UpdateWorkOrder(System.Xml.Linq.XElement requestXml) {
            return base.Channel.UpdateWorkOrder(requestXml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> UpdateWorkOrderAsync(System.Xml.Linq.XElement requestXml) {
            return base.Channel.UpdateWorkOrderAsync(requestXml);
        }
    }
}
