//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Branch1 = new HashSet<Branch>();
            this.NWC_Zone = new HashSet<NWC_Zone>();
            this.Staff = new HashSet<Staff>();
            this.UserBranchPermission = new HashSet<UserBranchPermission>();
            this.Landmark = new HashSet<Landmark>();
            this.Transporter = new HashSet<Transporter>();
            this.Transporter1 = new HashSet<Transporter>();
        }
    
        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public bool IsSubBranch { get; set; }
        public Nullable<System.Guid> parentBranchId { get; set; }
        public string descr { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string telephone2 { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<System.Guid> contactPerson { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid SubId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isPermenant { get; set; }
        public string prefix { get; set; }
        public string TankerSizes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branch1 { get; set; }
        public virtual Branch Branch2 { get; set; }
        public virtual ContactPerson ContactPerson1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_Zone> NWC_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBranchPermission> UserBranchPermission { get; set; }
        public virtual NWC_BranchSetting NWC_BranchSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Landmark> Landmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter> Transporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter> Transporter1 { get; set; }
    }
}
