//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELM_Tanker
    {
        public int ID { get; set; }
        public string DTO { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsInserted { get; set; }
        public string Exception { get; set; }
        public Nullable<int> retrials { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.Guid> permitNo { get; set; }
    }
}
