//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELMTransaction
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public Nullable<System.Guid> ELMTransactionId { get; set; }
        public Nullable<System.Guid> permitNo { get; set; }
        public string plateNo { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<bool> Value { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
    }
}
