//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Landmark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Landmark()
        {
            this.NWC_DeviceMeter = new HashSet<NWC_DeviceMeter>();
            this.NWC_StationCustomerLocationClass = new HashSet<NWC_StationCustomerLocationClass>();
            this.NWC_StationServiceType = new HashSet<NWC_StationServiceType>();
            this.NWC_UserLandmarkPermission = new HashSet<NWC_UserLandmarkPermission>();
            this.NWC_ZoneStations = new HashSet<NWC_ZoneStations>();
            this.NWC_ContractPrice = new HashSet<NWC_ContractPrice>();
            this.NWC_ContractStations = new HashSet<NWC_ContractStations>();
            this.NWC_ContractStationViolation = new HashSet<NWC_ContractStationViolation>();
            this.NWC_ContractAccessory = new HashSet<NWC_ContractAccessory>();
            this.NWC_ContractTerms = new HashSet<NWC_ContractTerms>();
            this.NWC_ContractTariff = new HashSet<NWC_ContractTariff>();
            this.Staff = new HashSet<Staff>();
            this.NWC_StationDefaultTankers = new HashSet<NWC_StationDefaultTankers>();
            this.Transporter = new HashSet<Transporter>();
            this.NWC_ViolationsApprovals = new HashSet<NWC_ViolationsApprovals>();
        }
    
        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> landmarkTypeId { get; set; }
        public string landmarkTypeName { get; set; }
        public Nullable<System.Guid> branchId { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string telephone2 { get; set; }
        public string mobile { get; set; }
        public string fax { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<System.Guid> contactPerson { get; set; }
        public System.Guid SubId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.Guid> GeofenceId { get; set; }
        public Nullable<int> AVGAddonFillingTime { get; set; }
        public Nullable<int> WaterSourceID { get; set; }
        public Nullable<int> StationOwnershipID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string IntegrationId { get; set; }
        public bool IsVirtualStation { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<int> DailyQuota { get; set; }
    
        public virtual NWC_StationOwnership NWC_StationOwnership { get; set; }
        public virtual NWC_StationStatus NWC_StationStatus { get; set; }
        public virtual NWC_StationWaterSource NWC_StationWaterSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_DeviceMeter> NWC_DeviceMeter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_StationCustomerLocationClass> NWC_StationCustomerLocationClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_StationServiceType> NWC_StationServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_UserLandmarkPermission> NWC_UserLandmarkPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ZoneStations> NWC_ZoneStations { get; set; }
        public virtual ContactPerson ContactPerson1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractPrice> NWC_ContractPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStations> NWC_ContractStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStationViolation> NWC_ContractStationViolation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractAccessory> NWC_ContractAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractTerms> NWC_ContractTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractTariff> NWC_ContractTariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_StationDefaultTankers> NWC_StationDefaultTankers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter> Transporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ViolationsApprovals> NWC_ViolationsApprovals { get; set; }
    }
}
