//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_StatusReason
    {
        public int ID { get; set; }
        public string ReasonAr { get; set; }
        public string ReasonEn { get; set; }
        public int StatusID { get; set; }
        public string IntegrationId { get; set; }
    
        public virtual NWC_WorkOrderStatus NWC_WorkOrderStatus { get; set; }
        public virtual TransporterStatus TransporterStatus { get; set; }
    }
}
