//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_RestrictedZoneVehicleType
    {
        public long ID { get; set; }
        public System.Guid VehicleTypeID { get; set; }
        public long ZoneID { get; set; }
    
        public virtual NWC_Zone NWC_Zone { get; set; }
        public virtual TransporterType TransporterType { get; set; }
    }
}
