//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ViolationsApprovalsLogs
    {
        public long ID { get; set; }
        public long ViolationID { get; set; }
        public long AprovalID { get; set; }
        public Nullable<int> DecisionType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual NWC_ContractTermsViolations NWC_ContractTermsViolations { get; set; }
        public virtual NWC_ViolationsApprovals NWC_ViolationsApprovals { get; set; }
    }
}
