//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Hayat_OrderStatusLog
    {
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreatedBy { get; set; }
        public int CurrentStatusID { get; set; }
        public int NewStatusID { get; set; }
        public string HayatRequest { get; set; }
        public string HayatResponse { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> Retrials { get; set; }
        public Nullable<System.DateTime> RetrialTime { get; set; }
    }
}
