//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ViolationsApprovals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_ViolationsApprovals()
        {
            this.NWC_ViolationsApprovalsLogs = new HashSet<NWC_ViolationsApprovalsLogs>();
        }
    
        public long ID { get; set; }
        public System.Guid LandmarkID { get; set; }
        public System.Guid StaffID { get; set; }
        public int LevelID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual Landmark Landmark { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ViolationsApprovalsLogs> NWC_ViolationsApprovalsLogs { get; set; }
    }
}
