//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTerms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_ContractTerms()
        {
            this.NWC_ContractStationViolation = new HashSet<NWC_ContractStationViolation>();
            this.NWC_ContractTermsViolations = new HashSet<NWC_ContractTermsViolations>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<long> TermsCategoryID { get; set; }
        public long ContractID { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> TotalValueUnitId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStationViolation> NWC_ContractStationViolation { get; set; }
        public virtual NWC_TermsCategory NWC_TermsCategory { get; set; }
        public virtual NWC_Contract NWC_Contract { get; set; }
        public virtual NWC_TermsValueUnits NWC_TermsValueUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractTermsViolations> NWC_ContractTermsViolations { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
