//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractStationViolation
    {
        public long ID { get; set; }
        public System.Guid StationID { get; set; }
        public long TermsID { get; set; }
        public long ViolationPaymentStatusID { get; set; }
        public Nullable<System.Guid> VehicleID { get; set; }
        public Nullable<System.Guid> StaffID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual NWC_ContractTerms NWC_ContractTerms { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Landmark Landmark { get; set; }
        public virtual Transporter Transporter { get; set; }
    }
}
