//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Event()
        {
            this.NWC_EventWorkOrder = new HashSet<NWC_EventWorkOrder>();
        }
    
        public long ID { get; set; }
        public System.Guid UserID { get; set; }
        public int EventTypeID { get; set; }
        public System.DateTime EventTime { get; set; }
        public string Remarks { get; set; }
        public System.Guid SubID { get; set; }
    
        public virtual NWC_EventType NWC_EventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_EventWorkOrder> NWC_EventWorkOrder { get; set; }
    }
}
