//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_EventWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_EventWorkOrder()
        {
            this.NWC_WorkOrderAccessory = new HashSet<NWC_WorkOrderAccessory>();
        }
    
        public long EventOrderID { get; set; }
        public Nullable<long> ParentWorkOrderID { get; set; }
        public long EventID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreatedBy { get; set; }
        public int StatusID { get; set; }
        public string StatusComment { get; set; }
        public Nullable<int> StatusReasonID { get; set; }
        public Nullable<int> DeassignReasonID { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<System.DateTime> ScheduledDeliveryTime { get; set; }
        public System.DateTime RequestTime { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public System.Guid SubID { get; set; }
        public string ConfirmationCode { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<System.Guid> VehicleID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<int> VehicleStatusID { get; set; }
        public string RecieverName { get; set; }
        public string RecieverMobile { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public Nullable<double> VehicleLatitude { get; set; }
        public Nullable<double> VehicleLongitude { get; set; }
        public string SourceApplication { get; set; }
        public string CISDivision { get; set; }
        public string TransactionID { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public Nullable<int> VehicleCustomerClassId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string VehicleCustomerClassesIds { get; set; }
        public int PriorityID { get; set; }
    
        public virtual NWC_DeassignReason NWC_DeassignReason { get; set; }
        public virtual NWC_Event NWC_Event { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderAccessory> NWC_WorkOrderAccessory { get; set; }
        public virtual NWC_WorkOrderTransaction NWC_WorkOrderTransaction { get; set; }
        public virtual Transporter Transporter { get; set; }
    }
}
