//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTermsViolations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_ContractTermsViolations()
        {
            this.NWC_ContractViolationAttachment = new HashSet<NWC_ContractViolationAttachment>();
            this.NWC_ViolationsApprovalsLogs = new HashSet<NWC_ViolationsApprovalsLogs>();
        }
    
        public long Id { get; set; }
        public long ContractTermId { get; set; }
        public string ViolationTicketNumber { get; set; }
        public string ViolationLocation { get; set; }
        public System.DateTime IncidentTime { get; set; }
        public decimal TotalPenalty { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public int PaymentStatusId { get; set; }
        public Nullable<System.DateTime> PaymentStatusDate { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public Nullable<System.Guid> DriverId { get; set; }
        public string Description { get; set; }
        public Nullable<int> TermUnitNoOfDays { get; set; }
        public bool AddVehicleToBlacklist { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CancelReasonId { get; set; }
        public Nullable<int> CurrentApprovalStatus { get; set; }
        public Nullable<System.DateTime> LastDecisionDate { get; set; }
        public Nullable<System.Guid> LastDecisionBy { get; set; }
        public bool IsFinalDecision { get; set; }
    
        public virtual NWC_ContractTerms NWC_ContractTerms { get; set; }
        public virtual NWC_WorkOrderInvoiceStatus NWC_WorkOrderInvoiceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractViolationAttachment> NWC_ContractViolationAttachment { get; set; }
        public virtual NWC_ContractTermsViolationStatus NWC_ContractTermsViolationStatus { get; set; }
        public virtual NWC_ContractTermsViolationCancelReason NWC_ContractTermsViolationCancelReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ViolationsApprovalsLogs> NWC_ViolationsApprovalsLogs { get; set; }
    }
}
