//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_CustomerAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_CustomerAccount()
        {
            this.NWC_StateWorkOrder = new HashSet<NWC_StateWorkOrder>();
            this.NWC_SoqyaSchedules = new HashSet<NWC_SoqyaSchedules>();
        }
    
        public long ID { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public string AccountId_Integration { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public Nullable<System.DateTime> EligibleStartDate { get; set; }
        public Nullable<System.DateTime> EligibleEndDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual NWC_CustomerLocation NWC_CustomerLocation { get; set; }
        public virtual NWC_ServiceType NWC_ServiceType { get; set; }
        public virtual NWC_Customer NWC_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_StateWorkOrder> NWC_StateWorkOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_SoqyaSchedules> NWC_SoqyaSchedules { get; set; }
    }
}
