//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Customer()
        {
            this.NWC_CustomerAccount = new HashSet<NWC_CustomerAccount>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public int IDTypeID { get; set; }
        public string IDNumber { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string LandlineNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid SubID { get; set; }
        public string IntegrationId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual NWC_PersonalIDType NWC_PersonalIDType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_CustomerAccount> NWC_CustomerAccount { get; set; }
    }
}
