//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_WorkOrderLog
    {
        public long ID { get; set; }
        public long WorkOrderId { get; set; }
        public int ActionLogTypeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusComment { get; set; }
        public Nullable<int> DeassignReasonID { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<decimal> NetCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<System.Guid> VehicleID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<int> VehicleStatusID { get; set; }
        public string RecieverName { get; set; }
        public string RecieverMobile { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ScheduledDeliveryTime { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public Nullable<double> VehicleLatitude { get; set; }
        public Nullable<double> VehicleLongitude { get; set; }
        public string SourceApplication { get; set; }
        public string CISDivision { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> StatusReasonId { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual NWC_ActionLogType NWC_ActionLogType { get; set; }
        public virtual NWC_DeassignReason NWC_DeassignReason { get; set; }
        public virtual NWC_StateWorkOrder NWC_StateWorkOrder { get; set; }
        public virtual NWC_WorkOrderStatus NWC_WorkOrderStatus { get; set; }
        public virtual TransporterStatus TransporterStatus { get; set; }
    }
}
