//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_VehicleLog
    {
        public long ID { get; set; }
        public System.Guid VehicleID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<long> WorkOrderID { get; set; }
        public int StatusID { get; set; }
        public int ActionLogTypeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CustomerClassesAr { get; set; }
        public string CustomerClassesEn { get; set; }
    }
}
