//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_StationServiceType
    {
        public long ID { get; set; }
        public System.Guid StationID { get; set; }
        public int ServiceTypeID { get; set; }
    
        public virtual NWC_ServiceType NWC_ServiceType { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
