//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTermsViolationsInvoices
    {
        public long Id { get; set; }
        public long ViolationId { get; set; }
        public string ViolationNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> ValueWithVAT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
