//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_UserLandmarkPermission
    {
        public long Id { get; set; }
        public System.Guid StaffId { get; set; }
        public System.Guid LandmarkID { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
