//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTermsViolationsLogs
    {
        public long Id { get; set; }
        public long TermViolationId { get; set; }
        public Nullable<long> ContractTermId { get; set; }
        public string ViolationTicketNumber { get; set; }
        public string ViolationLocation { get; set; }
        public Nullable<System.DateTime> IncidentTime { get; set; }
        public Nullable<decimal> TotalPenalty { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<System.DateTime> PaymentStatusDate { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public Nullable<System.Guid> DriverId { get; set; }
        public string Description { get; set; }
        public Nullable<int> TermUnitNoOfDays { get; set; }
        public bool AddVehicleToBlacklist { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CancelReasonId { get; set; }
        public string AttachementsDocumentsIds { get; set; }
        public string AttachementsDocumentsNames { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
