//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTerminationReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_ContractTerminationReason()
        {
            this.NWC_Contract = new HashSet<NWC_Contract>();
        }
    
        public int ID { get; set; }
        public string ReasonAr { get; set; }
        public string ReasonEn { get; set; }
        public System.Guid SubID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_Contract> NWC_Contract { get; set; }
    }
}
