//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_WorkOrderAccessory
    {
        public long ID { get; set; }
        public long WorkOrderID { get; set; }
        public int AccessoryID { get; set; }
    
        public virtual NWC_Accessory NWC_Accessory { get; set; }
        public virtual NWC_EventWorkOrder NWC_EventWorkOrder { get; set; }
    }
}
