//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_WorkOrderPlannedRout
    {
        public long ID { get; set; }
        public long WorkOrderID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string RouteJSON { get; set; }
        public string RouteLatLngString { get; set; }
        public Nullable<long> DrivingTime { get; set; }
        public Nullable<decimal> Distance { get; set; }
    }
}
