//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractAccessory
    {
        public long ID { get; set; }
        public long ContractID { get; set; }
        public System.Guid StationID { get; set; }
        public int AccessoryID { get; set; }
        public decimal Charge { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual NWC_Accessory NWC_Accessory { get; set; }
        public virtual NWC_Contract NWC_Contract { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
