//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_DeviceMeter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_DeviceMeter()
        {
            this.NWC_DeviceMeterReading = new HashSet<NWC_DeviceMeterReading>();
        }
    
        public long ID { get; set; }
        public string ConnectorTubeNumber { get; set; }
        public string MeterSerialNumber { get; set; }
        public string ManholeNumber { get; set; }
        public Nullable<bool> IsScadaAutoReading { get; set; }
        public int ServiceTypeID { get; set; }
        public System.Guid StationID { get; set; }
        public System.Guid SubID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_DeviceMeterReading> NWC_DeviceMeterReading { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
