//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_SoqyaSchedules
    {
        public long ID { get; set; }
        public long CustomerAccountId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> TimeSlotFrom { get; set; }
        public Nullable<System.TimeSpan> TimeSlotTo { get; set; }
        public int Quantity { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsGenerated { get; set; }
        public Nullable<System.DateTime> GeneratedTime { get; set; }
    
        public virtual NWC_CustomerAccount NWC_CustomerAccount { get; set; }
        public virtual NWC_StateWorkOrder NWC_StateWorkOrder { get; set; }
    }
}
