//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Zone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Zone()
        {
            this.NWC_ZoneStations = new HashSet<NWC_ZoneStations>();
            this.NWC_RestrictedZoneVehicleType = new HashSet<NWC_RestrictedZoneVehicleType>();
            this.NWC_CustomerLocation = new HashSet<NWC_CustomerLocation>();
        }
    
        public long ID { get; set; }
        public System.Guid CityID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.Guid SubID { get; set; }
        public string IntegrationId { get; set; }
        public Nullable<bool> ZoneWithoutTanker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ZoneStations> NWC_ZoneStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_RestrictedZoneVehicleType> NWC_RestrictedZoneVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_CustomerLocation> NWC_CustomerLocation { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
