//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_CustomerLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_CustomerLocation()
        {
            this.NWC_CustomerLocationBalance = new HashSet<NWC_CustomerLocationBalance>();
            this.NWC_CustomerAccount = new HashSet<NWC_CustomerAccount>();
        }
    
        public long ID { get; set; }
        public long CustomerID { get; set; }
        public string Code { get; set; }
        public long ZoneID { get; set; }
        public int ClassID { get; set; }
        public int PriorityID { get; set; }
        public int CategoryID { get; set; }
        public int StatusID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.Guid SubID { get; set; }
        public string IntegrationId { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Village { get; set; }
        public string Center { get; set; }
    
        public virtual NWC_CustomerLocationCategory NWC_CustomerLocationCategory { get; set; }
        public virtual NWC_CustomerLocationClass NWC_CustomerLocationClass { get; set; }
        public virtual NWC_CustomerLocationPriority NWC_CustomerLocationPriority { get; set; }
        public virtual NWC_CustomerLocationStatus NWC_CustomerLocationStatus { get; set; }
        public virtual NWC_Zone NWC_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_CustomerLocationBalance> NWC_CustomerLocationBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_CustomerAccount> NWC_CustomerAccount { get; set; }
    }
}
