//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_CustomerSMS
    {
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public System.Guid VehicleID { get; set; }
        public System.Guid DriverID { get; set; }
        public string DriverMobileNo { get; set; }
        public string CustomerMobileNo { get; set; }
        public string SMSText { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public string FailureMessage { get; set; }
    }
}
