//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_StateWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_StateWorkOrder()
        {
            this.NWC_WorkOrderComment = new HashSet<NWC_WorkOrderComment>();
            this.NWC_WorkOrderComplaint = new HashSet<NWC_WorkOrderComplaint>();
            this.NWC_WorkOrderLog = new HashSet<NWC_WorkOrderLog>();
            this.NWC_SoqyaSchedules = new HashSet<NWC_SoqyaSchedules>();
        }
    
        public long WorkOrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public int LastStatusID { get; set; }
        public Nullable<System.Guid> LastStatusBy { get; set; }
        public Nullable<System.DateTime> LastStatusTime { get; set; }
        public string LastStatusComment { get; set; }
        public string LastStatusReason { get; set; }
        public int OrderQuantity { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public System.DateTime RequestTime { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public decimal TotalCost { get; set; }
        public decimal NetCost { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> InvoiceStatusID { get; set; }
        public System.Guid AssignedStationID { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<System.Guid> AssignedVehicleID { get; set; }
        public Nullable<System.Guid> AssignedDriverID { get; set; }
        public Nullable<int> VehicleStatusID { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string ConfirmationCode { get; set; }
        public string EncryptedConfirmationCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid SubID { get; set; }
        public string RecieverName { get; set; }
        public string RecieverMobile { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AssignRetrials { get; set; }
        public Nullable<System.DateTime> AssignRetrialTime { get; set; }
        public Nullable<int> CancelRetrials { get; set; }
        public Nullable<System.DateTime> CancelRetrialTime { get; set; }
        public string SourceApplication { get; set; }
        public string CISDivision { get; set; }
        public string TransactionID { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Retrials { get; set; }
        public Nullable<System.DateTime> RetrialTime { get; set; }
        public Nullable<bool> ClosedByCode { get; set; }
        public int PriorityID { get; set; }
    
        public virtual NWC_CustomerAccount NWC_CustomerAccount { get; set; }
        public virtual NWC_WorkOrderInvoiceStatus NWC_WorkOrderInvoiceStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderComment> NWC_WorkOrderComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderComplaint> NWC_WorkOrderComplaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderLog> NWC_WorkOrderLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_SoqyaSchedules> NWC_SoqyaSchedules { get; set; }
    }
}
