//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_CustomerLocationBalance
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<long> BalanceLimit { get; set; }
        public long CustomerLocationID { get; set; }
        public int ServiceTypeID { get; set; }
        public int PaymentTypeID { get; set; }
        public int BalanceUniteID { get; set; }
    
        public virtual NWC_BalanceUnit NWC_BalanceUnit { get; set; }
        public virtual NWC_PaymentType NWC_PaymentType { get; set; }
        public virtual NWC_ServiceType NWC_ServiceType { get; set; }
        public virtual NWC_CustomerLocation NWC_CustomerLocation { get; set; }
    }
}
