//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_StationDefaultTankers
    {
        public long ID { get; set; }
        public System.Guid StationID { get; set; }
        public int Capacity { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Landmark Landmark { get; set; }
        public virtual NWC_TanckerCapacity NWC_TanckerCapacity { get; set; }
    }
}
