//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_WorkOrderComment
    {
        public long ID { get; set; }
        public long WorkOrderID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual NWC_StateWorkOrder NWC_StateWorkOrder { get; set; }
    }
}
