//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_ContractTariff
    {
        public long ID { get; set; }
        public long ContractID { get; set; }
        public System.Guid StationID { get; set; }
        public Nullable<long> ZoneID { get; set; }
        public int CustomerLocationClassID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public decimal CubicMeterCharge { get; set; }
        public decimal DistanceCharge { get; set; }
        public decimal AfterFirstKM { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TanckerCapacityId { get; set; }
        public Nullable<long> DateFromHijri { get; set; }
        public Nullable<long> DateToHijri { get; set; }
    
        public virtual NWC_Contract NWC_Contract { get; set; }
        public virtual NWC_TanckerCapacity NWC_TanckerCapacity { get; set; }
        public virtual NWC_CustomerLocationClass NWC_CustomerLocationClass { get; set; }
        public virtual NWC_ServiceType NWC_ServiceType { get; set; }
        public virtual Landmark Landmark { get; set; }
    }
}
