//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Contract()
        {
            this.NWC_ContractAccessory = new HashSet<NWC_ContractAccessory>();
            this.NWC_ContractAttachment = new HashSet<NWC_ContractAttachment>();
            this.NWC_ContractPrice = new HashSet<NWC_ContractPrice>();
            this.NWC_ContractStations = new HashSet<NWC_ContractStations>();
            this.NWC_ContractTerms = new HashSet<NWC_ContractTerms>();
            this.NWC_ContractTariff = new HashSet<NWC_ContractTariff>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public Nullable<System.DateTime> StatusChangedDate { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public Nullable<int> TerminationReasonID { get; set; }
        public long ContractorID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ContractStatusID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public System.Guid SubID { get; set; }
        public string ConfirmationNo { get; set; }
        public string AwardLetterNo { get; set; }
    
        public virtual NWC_Contractor NWC_Contractor { get; set; }
        public virtual NWC_ContractStatus NWC_ContractStatus { get; set; }
        public virtual NWC_ContractTerminationReason NWC_ContractTerminationReason { get; set; }
        public virtual NWC_ContractType NWC_ContractType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractAccessory> NWC_ContractAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractAttachment> NWC_ContractAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractPrice> NWC_ContractPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStations> NWC_ContractStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractTerms> NWC_ContractTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractTariff> NWC_ContractTariff { get; set; }
    }
}
