//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_DeviceMeterReading
    {
        public long ID { get; set; }
        public long DeviceMeterID { get; set; }
        public decimal MeterReading { get; set; }
        public System.DateTime ReadingTime { get; set; }
        public string ReadingComment { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> DetetedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual NWC_DeviceMeter NWC_DeviceMeter { get; set; }
    }
}
