//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_WorkOrderComplaint
    {
        public long ID { get; set; }
        public long WorkOrderID { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> RaisedBy { get; set; }
        public Nullable<System.DateTime> RaisedTime { get; set; }
        public int CategoryID { get; set; }
        public int PriorityID { get; set; }
        public int StatusID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual NWC_ComplaintCategory NWC_ComplaintCategory { get; set; }
        public virtual NWC_ComplaintPriority NWC_ComplaintPriority { get; set; }
        public virtual NWC_ComplaintStatus NWC_ComplaintStatus { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual NWC_StateWorkOrder NWC_StateWorkOrder { get; set; }
    }
}
