//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Contractor()
        {
            this.NWC_ContractorAttachment = new HashSet<NWC_ContractorAttachment>();
            this.NWC_Contract = new HashSet<NWC_Contract>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string ContractorFullName { get; set; }
        public string CommercialIDNumber { get; set; }
        public string TaxNumber { get; set; }
        public string MOI { get; set; }
        public System.Guid CompanyAddressCityID { get; set; }
        public string CompanyAddressPostalCode { get; set; }
        public string CompanyAddress { get; set; }
        public bool IsActive { get; set; }
        public bool IsBlackListed { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<long> ContactPersonId { get; set; }
    
        public virtual NWC_ContactPerson NWC_ContactPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractorAttachment> NWC_ContractorAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_Contract> NWC_Contract { get; set; }
    }
}
