//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NWCContext : DbContext
    {
        public NWCContext()
            : base("name=NWCContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<NWC_Accessory> NWC_Accessory { get; set; }
        public virtual DbSet<NWC_BalanceUnit> NWC_BalanceUnit { get; set; }
        public virtual DbSet<NWC_ComplaintCategory> NWC_ComplaintCategory { get; set; }
        public virtual DbSet<NWC_ComplaintPriority> NWC_ComplaintPriority { get; set; }
        public virtual DbSet<NWC_ComplaintStatus> NWC_ComplaintStatus { get; set; }
        public virtual DbSet<NWC_ContactPerson> NWC_ContactPerson { get; set; }
        public virtual DbSet<NWC_ContractTerminationReason> NWC_ContractTerminationReason { get; set; }
        public virtual DbSet<NWC_ContractType> NWC_ContractType { get; set; }
        public virtual DbSet<NWC_CustomerLocationPriority> NWC_CustomerLocationPriority { get; set; }
        public virtual DbSet<NWC_CustomerLocationStatus> NWC_CustomerLocationStatus { get; set; }
        public virtual DbSet<NWC_DeassignReason> NWC_DeassignReason { get; set; }
        public virtual DbSet<NWC_DeviceMeter> NWC_DeviceMeter { get; set; }
        public virtual DbSet<NWC_DeviceMeterReading> NWC_DeviceMeterReading { get; set; }
        public virtual DbSet<NWC_Event> NWC_Event { get; set; }
        public virtual DbSet<NWC_EventType> NWC_EventType { get; set; }
        public virtual DbSet<NWC_PaymentType> NWC_PaymentType { get; set; }
        public virtual DbSet<NWC_PersonalIDType> NWC_PersonalIDType { get; set; }
        public virtual DbSet<NWC_StationCustomerLocationClass> NWC_StationCustomerLocationClass { get; set; }
        public virtual DbSet<NWC_StationOwnership> NWC_StationOwnership { get; set; }
        public virtual DbSet<NWC_StationServiceType> NWC_StationServiceType { get; set; }
        public virtual DbSet<NWC_StationStatus> NWC_StationStatus { get; set; }
        public virtual DbSet<NWC_StationWaterSource> NWC_StationWaterSource { get; set; }
        public virtual DbSet<NWC_StatusReason> NWC_StatusReason { get; set; }
        public virtual DbSet<NWC_TermsCategory> NWC_TermsCategory { get; set; }
        public virtual DbSet<NWC_UserLandmarkPermission> NWC_UserLandmarkPermission { get; set; }
        public virtual DbSet<NWC_VehicleAccessory> NWC_VehicleAccessory { get; set; }
        public virtual DbSet<NWC_VehicleCustomerLocationClass> NWC_VehicleCustomerLocationClass { get; set; }
        public virtual DbSet<NWC_ViolationPaymentStatus> NWC_ViolationPaymentStatus { get; set; }
        public virtual DbSet<NWC_WorkOrderComplaint> NWC_WorkOrderComplaint { get; set; }
        public virtual DbSet<NWC_WorkOrderPlannedRout> NWC_WorkOrderPlannedRout { get; set; }
        public virtual DbSet<NWC_WorkOrderStatus> NWC_WorkOrderStatus { get; set; }
        public virtual DbSet<NWC_ZoneStations> NWC_ZoneStations { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<StaffRoles> StaffRoles { get; set; }
        public virtual DbSet<Transporter_Staff> Transporter_Staff { get; set; }
        public virtual DbSet<UserBranchPermission> UserBranchPermission { get; set; }
        public virtual DbSet<TransporterStatus> TransporterStatus { get; set; }
        public virtual DbSet<StaffRoleModulePermissions> StaffRoleModulePermissions { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<NWC_ActionLogType> NWC_ActionLogType { get; set; }
        public virtual DbSet<vw_NWC_ChangesLogs> vw_NWC_ChangesLogs { get; set; }
        public virtual DbSet<NWC_WorkOrderComment> NWC_WorkOrderComment { get; set; }
        public virtual DbSet<TransporterType> TransporterType { get; set; }
        public virtual DbSet<ContactPerson> ContactPerson { get; set; }
        public virtual DbSet<vw_NWC_ContractWorkOrderAccessory> vw_NWC_ContractWorkOrderAccessory { get; set; }
        public virtual DbSet<NWC_WorkOrderAccessory> NWC_WorkOrderAccessory { get; set; }
        public virtual DbSet<NWC_Zone> NWC_Zone { get; set; }
        public virtual DbSet<vw_NWC_ChangesLogsLocationData> vw_NWC_ChangesLogsLocationData { get; set; }
        public virtual DbSet<vw_NWC_ZoneList> vw_NWC_ZoneList { get; set; }
        public virtual DbSet<NWC_ContractAccessory> NWC_ContractAccessory { get; set; }
        public virtual DbSet<NWC_ContractPrice> NWC_ContractPrice { get; set; }
        public virtual DbSet<NWC_ContractStations> NWC_ContractStations { get; set; }
        public virtual DbSet<NWC_ContractStationViolation> NWC_ContractStationViolation { get; set; }
        public virtual DbSet<vw_NWC_ContractPriceList> vw_NWC_ContractPriceList { get; set; }
        public virtual DbSet<vw_NWC_ContractStations> vw_NWC_ContractStations { get; set; }
        public virtual DbSet<NWC_ContractTerms> NWC_ContractTerms { get; set; }
        public virtual DbSet<vw_NWC_ContractTerms> vw_NWC_ContractTerms { get; set; }
        public virtual DbSet<NWC_ContractAttachment> NWC_ContractAttachment { get; set; }
        public virtual DbSet<NWC_ContractStatus> NWC_ContractStatus { get; set; }
        public virtual DbSet<vw_NWC_ContractList> vw_NWC_ContractList { get; set; }
        public virtual DbSet<NWC_WorkOrderInvoiceStatus> NWC_WorkOrderInvoiceStatus { get; set; }
        public virtual DbSet<NWC_WorkOrderTransaction> NWC_WorkOrderTransaction { get; set; }
        public virtual DbSet<vw_NWC_ContractAccessory> vw_NWC_ContractAccessory { get; set; }
        public virtual DbSet<NWC_Contractor> NWC_Contractor { get; set; }
        public virtual DbSet<vw_NWC_ContractorList> vw_NWC_ContractorList { get; set; }
        public virtual DbSet<NWC_ContractorAttachment> NWC_ContractorAttachment { get; set; }
        public virtual DbSet<vw_NWC_DeviceMeterReading> vw_NWC_DeviceMeterReading { get; set; }
        public virtual DbSet<NWC_Contract> NWC_Contract { get; set; }
        public virtual DbSet<NWC_TanckerCapacity> NWC_TanckerCapacity { get; set; }
        public virtual DbSet<NWC_ContractTariff> NWC_ContractTariff { get; set; }
        public virtual DbSet<vw_NWC_ContractTariff> vw_NWC_ContractTariff { get; set; }
        public virtual DbSet<NWC_RestrictedZoneVehicleType> NWC_RestrictedZoneVehicleType { get; set; }
        public virtual DbSet<NWC_DeferredWorkOrder> NWC_DeferredWorkOrder { get; set; }
        public virtual DbSet<NWC_DeferredWorkOrderStatus> NWC_DeferredWorkOrderStatus { get; set; }
        public virtual DbSet<NWC_DriverSMS> NWC_DriverSMS { get; set; }
        public virtual DbSet<NWC_TermsValueUnits> NWC_TermsValueUnits { get; set; }
        public virtual DbSet<NWC_CustomerLocationBalance> NWC_CustomerLocationBalance { get; set; }
        public virtual DbSet<NWC_CustomerLocationCategory> NWC_CustomerLocationCategory { get; set; }
        public virtual DbSet<NWC_CustomerLocationClass> NWC_CustomerLocationClass { get; set; }
        public virtual DbSet<NWC_ServiceType> NWC_ServiceType { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<NWC_CustomerSMS> NWC_CustomerSMS { get; set; }
        public virtual DbSet<NWC_UserServicePermission> NWC_UserServicePermission { get; set; }
        public virtual DbSet<NWC_CustomerLocation> NWC_CustomerLocation { get; set; }
        public virtual DbSet<NWC_VehicleLogType> NWC_VehicleLogType { get; set; }
        public virtual DbSet<vw_NWC_StaffRoleModulePermissions> vw_NWC_StaffRoleModulePermissions { get; set; }
        public virtual DbSet<SubscriberAdminSettings> SubscriberAdminSettings { get; set; }
        public virtual DbSet<vw_NWC_Report_VehicleLog> vw_NWC_Report_VehicleLog { get; set; }
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<NWC_CustomerAccount> NWC_CustomerAccount { get; set; }
        public virtual DbSet<vw_NWC_CustomerAccount> vw_NWC_CustomerAccount { get; set; }
        public virtual DbSet<vw_NWC_Report_SoqyaSchedule> vw_NWC_Report_SoqyaSchedule { get; set; }
        public virtual DbSet<vw_NWC_Report_VehicleData> vw_NWC_Report_VehicleData { get; set; }
        public virtual DbSet<NWC_ContractViolationAttachment> NWC_ContractViolationAttachment { get; set; }
        public virtual DbSet<NWC_ContractTermsViolations> NWC_ContractTermsViolations { get; set; }
        public virtual DbSet<vw_NWC_AvailableTankerSizes> vw_NWC_AvailableTankerSizes { get; set; }
        public virtual DbSet<NWC_VehicleLog> NWC_VehicleLog { get; set; }
        public virtual DbSet<NWC_Customer> NWC_Customer { get; set; }
        public virtual DbSet<vw_NWC_CustomerAccountZone> vw_NWC_CustomerAccountZone { get; set; }
        public virtual DbSet<vw_NWC_CustomerAccountCity> vw_NWC_CustomerAccountCity { get; set; }
        public virtual DbSet<vw_NWC_VehicleNWCSettings> vw_NWC_VehicleNWCSettings { get; set; }
        public virtual DbSet<vw_NWC_VehicleViolation> vw_NWC_VehicleViolation { get; set; }
        public virtual DbSet<NWC_ContractTermsViolationStatus> NWC_ContractTermsViolationStatus { get; set; }
        public virtual DbSet<NWC_ContractTermsViolationCancelReason> NWC_ContractTermsViolationCancelReason { get; set; }
        public virtual DbSet<NWC_ContractTermsViolationsLogs> NWC_ContractTermsViolationsLogs { get; set; }
        public virtual DbSet<vw_NWC_ContractTermsViolationsLogs> vw_NWC_ContractTermsViolationsLogs { get; set; }
        public virtual DbSet<vw_NWC_PrintCustomerInvoice> vw_NWC_PrintCustomerInvoice { get; set; }
        public virtual DbSet<vw_NWC_PrintDriverInvoice> vw_NWC_PrintDriverInvoice { get; set; }
        public virtual DbSet<vw_NWC_PrintVehicleInvoice> vw_NWC_PrintVehicleInvoice { get; set; }
        public virtual DbSet<vw_NWC_UserLandmarkPermission> vw_NWC_UserLandmarkPermission { get; set; }
        public virtual DbSet<NWC_WorkOrderCategory> NWC_WorkOrderCategory { get; set; }
        public virtual DbSet<vw_NWC_ContractTermsViolations> vw_NWC_ContractTermsViolations { get; set; }
        public virtual DbSet<NWC_StateWorkOrder> NWC_StateWorkOrder { get; set; }
        public virtual DbSet<NWC_WorkOrderLog> NWC_WorkOrderLog { get; set; }
        public virtual DbSet<vw_NWC_WorkOrderLogs> vw_NWC_WorkOrderLogs { get; set; }
        public virtual DbSet<vw_NWC_Report_StationOrderCapacitySummary> vw_NWC_Report_StationOrderCapacitySummary { get; set; }
        public virtual DbSet<vw_NWC_Report_TankersPermissionsStatus> vw_NWC_Report_TankersPermissionsStatus { get; set; }
        public virtual DbSet<NWC_Hayat_OrderStatusLog> NWC_Hayat_OrderStatusLog { get; set; }
        public virtual DbSet<NWC_ContractTermsViolationsInvoices> NWC_ContractTermsViolationsInvoices { get; set; }
        public virtual DbSet<vw_NWC_ContractTermsViolationsInvoices> vw_NWC_ContractTermsViolationsInvoices { get; set; }
        public virtual DbSet<NWC_SoqyaSchedules> NWC_SoqyaSchedules { get; set; }
        public virtual DbSet<vw_NWC_SoqyaSchedule> vw_NWC_SoqyaSchedule { get; set; }
        public virtual DbSet<vw_NWC_Report_StationServiceTimeSummary> vw_NWC_Report_StationServiceTimeSummary { get; set; }
        public virtual DbSet<vw_NWC_Report_SoqyaScheduledQuantities> vw_NWC_Report_SoqyaScheduledQuantities { get; set; }
        public virtual DbSet<NWC_BranchSetting> NWC_BranchSetting { get; set; }
        public virtual DbSet<vw_NWC_Report_OrdersPerZone> vw_NWC_Report_OrdersPerZone { get; set; }
        public virtual DbSet<vw_NWC_AssignableVehicles> vw_NWC_AssignableVehicles { get; set; }
        public virtual DbSet<StaffRoleCategory> StaffRoleCategory { get; set; }
        public virtual DbSet<TransporterBrand> TransporterBrand { get; set; }
        public virtual DbSet<TransporterGroup> TransporterGroup { get; set; }
        public virtual DbSet<TransporterProductionYear> TransporterProductionYear { get; set; }
        public virtual DbSet<TransporterManufacturer> TransporterManufacturer { get; set; }
        public virtual DbSet<vw_NWC_StateVehicle> vw_NWC_StateVehicle { get; set; }
        public virtual DbSet<vw_NWC_WorkOrderVehicle> vw_NWC_WorkOrderVehicle { get; set; }
        public virtual DbSet<vw_NWC_Report_DailyOrderDetails> vw_NWC_Report_DailyOrderDetails { get; set; }
        public virtual DbSet<vw_NWC_LandmarkNWCSettings> vw_NWC_LandmarkNWCSettings { get; set; }
        public virtual DbSet<vw_NWC_WorkOrderList> vw_NWC_WorkOrderList { get; set; }
        public virtual DbSet<vw_NWC_WorkOrderBasicDetails> vw_NWC_WorkOrderBasicDetails { get; set; }
        public virtual DbSet<vw_NWC_Report_OrderReassignment> vw_NWC_Report_OrderReassignment { get; set; }
        public virtual DbSet<NWC_EventWorkOrder> NWC_EventWorkOrder { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<Landmark> Landmark { get; set; }
        public virtual DbSet<ELM_Tanker> ELM_Tanker { get; set; }
        public virtual DbSet<PermitDeclarationAttachment> PermitDeclarationAttachment { get; set; }
        public virtual DbSet<PermitDetectionformAttachment> PermitDetectionformAttachment { get; set; }
        public virtual DbSet<PermitOtherFIleAttachment> PermitOtherFIleAttachment { get; set; }
        public virtual DbSet<vw_NWC_StationSizes> vw_NWC_StationSizes { get; set; }
        public virtual DbSet<NWC_StationDefaultTankers> NWC_StationDefaultTankers { get; set; }
        public virtual DbSet<ELMTransaction> ELMTransaction { get; set; }
        public virtual DbSet<vw_NWC_Report_DailyOrderSummary> vw_NWC_Report_DailyOrderSummary { get; set; }
        public virtual DbSet<Permit> Permit { get; set; }
        public virtual DbSet<vw_permitList> vw_permitList { get; set; }
        public virtual DbSet<Transporter> Transporter { get; set; }
        public virtual DbSet<NWC_ViolationsApprovals> NWC_ViolationsApprovals { get; set; }
        public virtual DbSet<NWC_ViolationsApprovalsLogs> NWC_ViolationsApprovalsLogs { get; set; }
        public virtual DbSet<vw_NWC_ZoneWithNoPrices> vw_NWC_ZoneWithNoPrices { get; set; }
        public virtual DbSet<vw_NWC_BranchSetting> vw_NWC_BranchSetting { get; set; }
        public virtual DbSet<vw_NWC_ViolationsApprovals> vw_NWC_ViolationsApprovals { get; set; }
        public virtual DbSet<vw_NWC_ViolationsApprovalsLogs> vw_NWC_ViolationsApprovalsLogs { get; set; }
    
        public virtual int sp_NWC_GetAssignableWorkOrders(Nullable<System.Guid> subID, Nullable<int> statusId, Nullable<System.Guid> vehicleID, string orderBy, Nullable<int> take, Nullable<int> skip)
        {
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var vehicleIDParameter = vehicleID.HasValue ?
                new ObjectParameter("VehicleID", vehicleID) :
                new ObjectParameter("VehicleID", typeof(System.Guid));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NWC_GetAssignableWorkOrders", subIDParameter, statusIdParameter, vehicleIDParameter, orderByParameter, takeParameter, skipParameter);
        }
    
        public virtual ObjectResult<sp_NWC_WorkOrderList_Result> sp_NWC_WorkOrderList(Nullable<System.Guid> staffID, Nullable<System.Guid> subID, Nullable<bool> isDeleted, string workOrderNumber, string customerIDs, string classIDs, string priorityIDs, string serviceTypeIDs, string cityIDs, string zoneIDs, string stationIDs, string statusIDs, string vehicleIDs, string driverIDs, Nullable<int> dateToSearch, Nullable<System.DateTime> requestTimeFrom, Nullable<System.DateTime> requestTimeTo, Nullable<System.DateTime> scheduledDeliveryTimeFrom, Nullable<System.DateTime> scheduledDeliveryTimeTo, Nullable<System.DateTime> lastStatusTimeFrom, Nullable<System.DateTime> lastStatusTimeTo, string orderBy, Nullable<int> take, Nullable<int> skip)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(System.Guid));
    
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(bool));
    
            var workOrderNumberParameter = workOrderNumber != null ?
                new ObjectParameter("WorkOrderNumber", workOrderNumber) :
                new ObjectParameter("WorkOrderNumber", typeof(string));
    
            var customerIDsParameter = customerIDs != null ?
                new ObjectParameter("CustomerIDs", customerIDs) :
                new ObjectParameter("CustomerIDs", typeof(string));
    
            var classIDsParameter = classIDs != null ?
                new ObjectParameter("ClassIDs", classIDs) :
                new ObjectParameter("ClassIDs", typeof(string));
    
            var priorityIDsParameter = priorityIDs != null ?
                new ObjectParameter("PriorityIDs", priorityIDs) :
                new ObjectParameter("PriorityIDs", typeof(string));
    
            var serviceTypeIDsParameter = serviceTypeIDs != null ?
                new ObjectParameter("ServiceTypeIDs", serviceTypeIDs) :
                new ObjectParameter("ServiceTypeIDs", typeof(string));
    
            var cityIDsParameter = cityIDs != null ?
                new ObjectParameter("CityIDs", cityIDs) :
                new ObjectParameter("CityIDs", typeof(string));
    
            var zoneIDsParameter = zoneIDs != null ?
                new ObjectParameter("ZoneIDs", zoneIDs) :
                new ObjectParameter("ZoneIDs", typeof(string));
    
            var stationIDsParameter = stationIDs != null ?
                new ObjectParameter("StationIDs", stationIDs) :
                new ObjectParameter("StationIDs", typeof(string));
    
            var statusIDsParameter = statusIDs != null ?
                new ObjectParameter("StatusIDs", statusIDs) :
                new ObjectParameter("StatusIDs", typeof(string));
    
            var vehicleIDsParameter = vehicleIDs != null ?
                new ObjectParameter("VehicleIDs", vehicleIDs) :
                new ObjectParameter("VehicleIDs", typeof(string));
    
            var driverIDsParameter = driverIDs != null ?
                new ObjectParameter("DriverIDs", driverIDs) :
                new ObjectParameter("DriverIDs", typeof(string));
    
            var dateToSearchParameter = dateToSearch.HasValue ?
                new ObjectParameter("DateToSearch", dateToSearch) :
                new ObjectParameter("DateToSearch", typeof(int));
    
            var requestTimeFromParameter = requestTimeFrom.HasValue ?
                new ObjectParameter("RequestTimeFrom", requestTimeFrom) :
                new ObjectParameter("RequestTimeFrom", typeof(System.DateTime));
    
            var requestTimeToParameter = requestTimeTo.HasValue ?
                new ObjectParameter("RequestTimeTo", requestTimeTo) :
                new ObjectParameter("RequestTimeTo", typeof(System.DateTime));
    
            var scheduledDeliveryTimeFromParameter = scheduledDeliveryTimeFrom.HasValue ?
                new ObjectParameter("ScheduledDeliveryTimeFrom", scheduledDeliveryTimeFrom) :
                new ObjectParameter("ScheduledDeliveryTimeFrom", typeof(System.DateTime));
    
            var scheduledDeliveryTimeToParameter = scheduledDeliveryTimeTo.HasValue ?
                new ObjectParameter("ScheduledDeliveryTimeTo", scheduledDeliveryTimeTo) :
                new ObjectParameter("ScheduledDeliveryTimeTo", typeof(System.DateTime));
    
            var lastStatusTimeFromParameter = lastStatusTimeFrom.HasValue ?
                new ObjectParameter("LastStatusTimeFrom", lastStatusTimeFrom) :
                new ObjectParameter("LastStatusTimeFrom", typeof(System.DateTime));
    
            var lastStatusTimeToParameter = lastStatusTimeTo.HasValue ?
                new ObjectParameter("LastStatusTimeTo", lastStatusTimeTo) :
                new ObjectParameter("LastStatusTimeTo", typeof(System.DateTime));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_WorkOrderList_Result>("sp_NWC_WorkOrderList", staffIDParameter, subIDParameter, isDeletedParameter, workOrderNumberParameter, customerIDsParameter, classIDsParameter, priorityIDsParameter, serviceTypeIDsParameter, cityIDsParameter, zoneIDsParameter, stationIDsParameter, statusIDsParameter, vehicleIDsParameter, driverIDsParameter, dateToSearchParameter, requestTimeFromParameter, requestTimeToParameter, scheduledDeliveryTimeFromParameter, scheduledDeliveryTimeToParameter, lastStatusTimeFromParameter, lastStatusTimeToParameter, orderByParameter, takeParameter, skipParameter);
        }
    
        public virtual ObjectResult<sp_NWC_DashboardOrdersCountsViceExcuteTime_Result> sp_NWC_DashboardOrdersCountsViceExcuteTime(Nullable<System.Guid> subID, string stationIDs, Nullable<int> serviceTypeID, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var stationIDsParameter = stationIDs != null ?
                new ObjectParameter("StationIDs", stationIDs) :
                new ObjectParameter("StationIDs", typeof(string));
    
            var serviceTypeIDParameter = serviceTypeID.HasValue ?
                new ObjectParameter("ServiceTypeID", serviceTypeID) :
                new ObjectParameter("ServiceTypeID", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_DashboardOrdersCountsViceExcuteTime_Result>("sp_NWC_DashboardOrdersCountsViceExcuteTime", subIDParameter, stationIDsParameter, serviceTypeIDParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<sp_NWC_GetAssignableWorkOrders_Result> sp_NWC_GetAssignableWorkOrders_Result(Nullable<System.Guid> subID, Nullable<int> statusId, Nullable<System.Guid> vehicleID, string orderBy, Nullable<int> take, Nullable<int> skip)
        {
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            var vehicleIDParameter = vehicleID.HasValue ?
                new ObjectParameter("VehicleID", vehicleID) :
                new ObjectParameter("VehicleID", typeof(System.Guid));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_GetAssignableWorkOrders_Result>("sp_NWC_GetAssignableWorkOrders_Result", subIDParameter, statusIdParameter, vehicleIDParameter, orderByParameter, takeParameter, skipParameter);
        }
    
        public virtual ObjectResult<sp_NWC_GetAssignableVehicles_Result> sp_NWC_GetAssignableVehicles_Result(Nullable<System.Guid> subID, Nullable<long> workOrderID, Nullable<int> orderQuantity, Nullable<long> zoneID, Nullable<System.Guid> stationID, Nullable<int> vehicleStatusId, Nullable<int> serviceTypeID, Nullable<int> classID)
        {
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var workOrderIDParameter = workOrderID.HasValue ?
                new ObjectParameter("WorkOrderID", workOrderID) :
                new ObjectParameter("WorkOrderID", typeof(long));
    
            var orderQuantityParameter = orderQuantity.HasValue ?
                new ObjectParameter("OrderQuantity", orderQuantity) :
                new ObjectParameter("OrderQuantity", typeof(int));
    
            var zoneIDParameter = zoneID.HasValue ?
                new ObjectParameter("ZoneID", zoneID) :
                new ObjectParameter("ZoneID", typeof(long));
    
            var stationIDParameter = stationID.HasValue ?
                new ObjectParameter("StationID", stationID) :
                new ObjectParameter("StationID", typeof(System.Guid));
    
            var vehicleStatusIdParameter = vehicleStatusId.HasValue ?
                new ObjectParameter("VehicleStatusId", vehicleStatusId) :
                new ObjectParameter("VehicleStatusId", typeof(int));
    
            var serviceTypeIDParameter = serviceTypeID.HasValue ?
                new ObjectParameter("ServiceTypeID", serviceTypeID) :
                new ObjectParameter("ServiceTypeID", typeof(int));
    
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("ClassID", classID) :
                new ObjectParameter("ClassID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_GetAssignableVehicles_Result>("sp_NWC_GetAssignableVehicles_Result", subIDParameter, workOrderIDParameter, orderQuantityParameter, zoneIDParameter, stationIDParameter, vehicleStatusIdParameter, serviceTypeIDParameter, classIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> sp_NWC_SeqNextValue_ContractTermViolationInvoice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("sp_NWC_SeqNextValue_ContractTermViolationInvoice");
        }
    
        public virtual ObjectResult<Nullable<long>> sp_NWC_SeqNextValue_OrderInvoice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("sp_NWC_SeqNextValue_OrderInvoice");
        }
    
        public virtual ObjectResult<sp_NWC_Report_VehiclePerformance_Result> sp_NWC_Report_VehiclePerformance(Nullable<int> pageIndex, Nullable<int> pageSize, Nullable<System.Guid> subID, string areaIDs, string cityIDs, string stationIDs, string serviceTypeIDs, string vehicleCode, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var areaIDsParameter = areaIDs != null ?
                new ObjectParameter("AreaIDs", areaIDs) :
                new ObjectParameter("AreaIDs", typeof(string));
    
            var cityIDsParameter = cityIDs != null ?
                new ObjectParameter("CityIDs", cityIDs) :
                new ObjectParameter("CityIDs", typeof(string));
    
            var stationIDsParameter = stationIDs != null ?
                new ObjectParameter("StationIDs", stationIDs) :
                new ObjectParameter("StationIDs", typeof(string));
    
            var serviceTypeIDsParameter = serviceTypeIDs != null ?
                new ObjectParameter("ServiceTypeIDs", serviceTypeIDs) :
                new ObjectParameter("ServiceTypeIDs", typeof(string));
    
            var vehicleCodeParameter = vehicleCode != null ?
                new ObjectParameter("VehicleCode", vehicleCode) :
                new ObjectParameter("VehicleCode", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_Report_VehiclePerformance_Result>("sp_NWC_Report_VehiclePerformance", pageIndexParameter, pageSizeParameter, subIDParameter, areaIDsParameter, cityIDsParameter, stationIDsParameter, serviceTypeIDsParameter, vehicleCodeParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<sp_NWC_Report_OrderReassignment_Result> sp_NWC_Report_OrderReassignment(Nullable<int> pageIndex, Nullable<int> pageSize, Nullable<System.Guid> subID, string areaIDs, string cityIDs, string stationIDs, string oldTanker, string newTanker, string orderNumber, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var subIDParameter = subID.HasValue ?
                new ObjectParameter("SubID", subID) :
                new ObjectParameter("SubID", typeof(System.Guid));
    
            var areaIDsParameter = areaIDs != null ?
                new ObjectParameter("AreaIDs", areaIDs) :
                new ObjectParameter("AreaIDs", typeof(string));
    
            var cityIDsParameter = cityIDs != null ?
                new ObjectParameter("CityIDs", cityIDs) :
                new ObjectParameter("CityIDs", typeof(string));
    
            var stationIDsParameter = stationIDs != null ?
                new ObjectParameter("StationIDs", stationIDs) :
                new ObjectParameter("StationIDs", typeof(string));
    
            var oldTankerParameter = oldTanker != null ?
                new ObjectParameter("OldTanker", oldTanker) :
                new ObjectParameter("OldTanker", typeof(string));
    
            var newTankerParameter = newTanker != null ?
                new ObjectParameter("NewTanker", newTanker) :
                new ObjectParameter("NewTanker", typeof(string));
    
            var orderNumberParameter = orderNumber != null ?
                new ObjectParameter("OrderNumber", orderNumber) :
                new ObjectParameter("OrderNumber", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_NWC_Report_OrderReassignment_Result>("sp_NWC_Report_OrderReassignment", pageIndexParameter, pageSizeParameter, subIDParameter, areaIDsParameter, cityIDsParameter, stationIDsParameter, oldTankerParameter, newTankerParameter, orderNumberParameter, dateFromParameter, dateToParameter);
        }
    }
}
