//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pages()
        {
            this.StaffRoles = new HashSet<StaffRoles>();
            this.StaffRoleModulePermissions = new HashSet<StaffRoleModulePermissions>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.Guid ModuleID { get; set; }
        public string UniqueName { get; set; }
        public string Path { get; set; }
        public bool IsGPS { get; set; }
        public bool IsCarRental { get; set; }
        public bool IsMaintenance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoles> StaffRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoleModulePermissions> StaffRoleModulePermissions { get; set; }
        public virtual Modules Modules { get; set; }
    }
}
