//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<System.Guid> TransporterID { get; set; }
        public string PermitNumber { get; set; }
        public string Discerption { get; set; }
        public string OrganizationName { get; set; }
        public string CRnumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public string Availabletimefrom { get; set; }
        public string Availabletimeto { get; set; }
        public string TankerCategory { get; set; }
        public Nullable<System.DateTime> LastValidationDate { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDate { get; set; }
        public Nullable<bool> Ismaramy { get; set; }
        public string Maramu { get; set; }
        public string TripsNumber { get; set; }
        public string DetectionformFile { get; set; }
        public string DeclarationFile { get; set; }
        public string OtherFile { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<int> PermitStatus { get; set; }
        public Nullable<bool> IsHold { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Transporter Transporter { get; set; }
    }
}
