//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.NWC_ContractStationViolation = new HashSet<NWC_ContractStationViolation>();
            this.NWC_UserLandmarkPermission = new HashSet<NWC_UserLandmarkPermission>();
            this.NWC_WorkOrderComment = new HashSet<NWC_WorkOrderComment>();
            this.NWC_WorkOrderComplaint = new HashSet<NWC_WorkOrderComplaint>();
            this.Transporter_Staff = new HashSet<Transporter_Staff>();
            this.UserBranchPermission = new HashSet<UserBranchPermission>();
            this.NWC_UserServicePermission = new HashSet<NWC_UserServicePermission>();
            this.NWC_EventWorkOrder = new HashSet<NWC_EventWorkOrder>();
            this.Permit = new HashSet<Permit>();
            this.NWC_ViolationsApprovals = new HashSet<NWC_ViolationsApprovals>();
        }
    
        public System.Guid ID { get; set; }
        public string FirstName { get; set; }
        public string descr { get; set; }
        public string code { get; set; }
        public System.Guid subID { get; set; }
        public Nullable<System.Guid> staffRoleID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string image { get; set; }
        public bool isAllocated { get; set; }
        public string personalID { get; set; }
        public Nullable<System.Guid> AllocatedBranch { get; set; }
        public Nullable<System.Guid> AllocatedLandmark { get; set; }
        public Nullable<System.Guid> status { get; set; }
        public Nullable<System.Guid> employmentType { get; set; }
        public Nullable<System.DateTime> employmentDate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string mobileNumber { get; set; }
        public Nullable<bool> MonitorFlag { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<double> LaborRate { get; set; }
        public string LisenceNumber { get; set; }
        public Nullable<System.DateTime> LisenceIssueDate { get; set; }
        public Nullable<System.DateTime> LisenceExpiryDate { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<System.DateTime> InsuranceIssueDate { get; set; }
        public Nullable<System.Guid> InsuranceCompanyID { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string EmergencyContactName1 { get; set; }
        public string EmergencyContactName2 { get; set; }
        public string EmergencyContactPhone1 { get; set; }
        public string EmergencyContactPhone2 { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Email { get; set; }
        public string StaffRoleName { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string EmploymentDateHijri { get; set; }
        public string HireDateHijri { get; set; }
        public string LicenseIssueDateHijri { get; set; }
        public string LicenseExpiryDateHijri { get; set; }
        public string InsuranceIssueDateHijri { get; set; }
        public string BirthdayHijri { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStationViolation> NWC_ContractStationViolation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_UserLandmarkPermission> NWC_UserLandmarkPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderComment> NWC_WorkOrderComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_WorkOrderComplaint> NWC_WorkOrderComplaint { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual StaffRoles StaffRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter_Staff> Transporter_Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBranchPermission> UserBranchPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_UserServicePermission> NWC_UserServicePermission { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_EventWorkOrder> NWC_EventWorkOrder { get; set; }
        public virtual Landmark Landmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit> Permit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ViolationsApprovals> NWC_ViolationsApprovals { get; set; }
    }
}
