//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoleModulePermissions
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> StaffRoleID { get; set; }
        public Nullable<System.Guid> AspNetRoleID { get; set; }
        public Nullable<System.Guid> ModuleID { get; set; }
        public Nullable<System.Guid> PageID { get; set; }
        public Nullable<System.Guid> SubID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
    
        public virtual Pages Pages { get; set; }
        public virtual StaffRoles StaffRoles { get; set; }
        public virtual Modules Modules { get; set; }
        public virtual aspnet_Roles aspnet_Roles { get; set; }
    }
}
