//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffRoles()
        {
            this.StaffRoleModulePermissions = new HashSet<StaffRoleModulePermissions>();
            this.Staff = new HashSet<Staff>();
        }
    
        public System.Guid ID { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public System.Guid subID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public short category { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public Nullable<bool> isModified { get; set; }
        public string Icon { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.Guid> PageId { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
    
        public virtual Pages Pages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffRoleModulePermissions> StaffRoleModulePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual StaffRoleCategory StaffRoleCategory { get; set; }
    }
}
