//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberAdminSettings
    {
        public System.Guid SubID { get; set; }
        public string applicationLogo { get; set; }
        public string billingLogo { get; set; }
        public string billingFooter { get; set; }
        public Nullable<bool> SMAlert { get; set; }
        public Nullable<bool> MileageConflictAlert { get; set; }
        public Nullable<bool> RFMWarning { get; set; }
        public Nullable<bool> WOWarning { get; set; }
        public Nullable<int> RFMWarningDays { get; set; }
        public Nullable<int> WOWarningDays { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> DefaultMap { get; set; }
        public string Currancy { get; set; }
        public Nullable<System.Guid> FK_Currency { get; set; }
        public Nullable<bool> IsCostIntegration { get; set; }
        public Nullable<bool> IsProjectBase { get; set; }
        public string DefaultLanguage { get; set; }
        public Nullable<int> MaxFailedPassword { get; set; }
        public Nullable<int> MinPasswordLength { get; set; }
        public Nullable<int> MaxPasswordAge { get; set; }
        public Nullable<bool> IdleUseIgnitionIfExists { get; set; }
        public Nullable<short> IdleTimeMinSettings { get; set; }
        public Nullable<int> PasswordsHistoryNo { get; set; }
        public Nullable<int> MinTimeForDisconnectedAlert { get; set; }
    }
}
