//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter_Staff
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Transporter { get; set; }
        public Nullable<System.Guid> Staff { get; set; }
        public System.Guid SubId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public Nullable<System.DateTime> OwnershipDate { get; set; }
        public Nullable<System.DateTime> VehicleReceivingDate { get; set; }
    
        public virtual Staff Staff1 { get; set; }
        public virtual Transporter Transporter1 { get; set; }
    }
}
