//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporter()
        {
            this.NWC_ContractStationViolation = new HashSet<NWC_ContractStationViolation>();
            this.NWC_EventWorkOrder = new HashSet<NWC_EventWorkOrder>();
            this.NWC_VehicleAccessory = new HashSet<NWC_VehicleAccessory>();
            this.NWC_VehicleCustomerLocationClass = new HashSet<NWC_VehicleCustomerLocationClass>();
            this.Permit = new HashSet<Permit>();
            this.Transporter_Staff = new HashSet<Transporter_Staff>();
        }
    
        public System.Guid ID { get; set; }
        public string code { get; set; }
        public string plateNo { get; set; }
        public string transporterTypeName { get; set; }
        public Nullable<System.Guid> transporterType { get; set; }
        public Nullable<System.Guid> branch { get; set; }
        public Nullable<System.Guid> landmark { get; set; }
        public double maxSpeed { get; set; }
        public decimal literPerKm { get; set; }
        public Nullable<double> currentMileage { get; set; }
        public string image { get; set; }
        public string color { get; set; }
        public Nullable<System.Guid> transporterBrand { get; set; }
        public Nullable<System.Guid> transporterProductionYear { get; set; }
        public Nullable<System.Guid> transporterManufacturer { get; set; }
        public Nullable<bool> deviceType { get; set; }
        public string SIMCardNo { get; set; }
        public string providerName { get; set; }
        public string deviceCode { get; set; }
        public string licenseNo { get; set; }
        public Nullable<System.DateTime> licenseExpiryDate { get; set; }
        public string chassisNo { get; set; }
        public string engineNo { get; set; }
        public Nullable<System.DateTime> entranceDate { get; set; }
        public string insuranceNo { get; set; }
        public string insuredBy { get; set; }
        public Nullable<System.DateTime> insuranceStartDate { get; set; }
        public Nullable<System.DateTime> insuranceEndDate { get; set; }
        public Nullable<System.Guid> supplier { get; set; }
        public Nullable<bool> isMonitored { get; set; }
        public System.Guid SubID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public string SupplierName { get; set; }
        public string LisenceImage { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> HourRate { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public Nullable<decimal> TempSensorMinValue { get; set; }
        public Nullable<decimal> TempSensorMaxValue { get; set; }
        public Nullable<System.Guid> DeviceID { get; set; }
        public Nullable<System.DateTime> NextExaminationDate { get; set; }
        public string CurrentSituationNote { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<double> FuelCalibrationConst_A { get; set; }
        public Nullable<double> FuelCalibrationConst_B { get; set; }
        public Nullable<double> FuelCalibrationConst_C { get; set; }
        public Nullable<double> FuelCalibrationConst_D { get; set; }
        public Nullable<double> TotalWorkingHours { get; set; }
        public Nullable<double> TankCapacity { get; set; }
        public Nullable<double> AnalogInputOneMin { get; set; }
        public Nullable<double> AnalogInputOneMax { get; set; }
        public Nullable<double> AnalogInputTwoMin { get; set; }
        public Nullable<double> AnalogInputTwoMax { get; set; }
        public Nullable<double> AnalogInputThreeMin { get; set; }
        public Nullable<double> AnalogInputThreeMax { get; set; }
        public Nullable<double> AnalogInputFourMin { get; set; }
        public Nullable<double> AnalogInputFourMax { get; set; }
        public Nullable<System.Guid> OldPlace { get; set; }
        public Nullable<System.DateTime> currentMileageLastModificationDate { get; set; }
        public Nullable<System.Guid> TransporterFuelTypeId { get; set; }
        public Nullable<System.Guid> TransporterInsuranceTypeId { get; set; }
        public string plateNo_Numbers { get; set; }
        public string plateNo_Characters { get; set; }
        public Nullable<long> TransporterLicenseType { get; set; }
        public Nullable<long> TransporterColor { get; set; }
        public string ShomooseRecordId { get; set; }
        public string TrackerProviderNameEn { get; set; }
        public string TrackerProviderNameAr { get; set; }
        public string TrackerBrandNameEn { get; set; }
        public string TrackerBrandNameAr { get; set; }
        public string TrackerModelNameEn { get; set; }
        public string TrackerModelNameAr { get; set; }
        public string LicenseExpiryDateHijri { get; set; }
        public string NextExaminationDateHijri { get; set; }
        public string EntranceDateHijri { get; set; }
        public string InsuranceStartDateHijri { get; set; }
        public string InsuranceEndDateHijri { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseExpiryDate { get; set; }
        public string LeaseStartDateHijri { get; set; }
        public string LeaseExpiryDateHijri { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> CapacityUnit { get; set; }
        public string petroleumcard { get; set; }
        public Nullable<int> CreditLimitId { get; set; }
        public string DieselCard { get; set; }
        public Nullable<long> VendorID { get; set; }
        public Nullable<System.Guid> providerId { get; set; }
        public string CreditLimit { get; set; }
        public Nullable<int> TrafficCodeId { get; set; }
        public Nullable<int> CheckingTransactionStatusId { get; set; }
        public Nullable<System.Guid> InsuranceCompony { get; set; }
        public Nullable<System.Guid> Insurance_Company { get; set; }
        public Nullable<short> FuelSensorType { get; set; }
        public Nullable<int> LoadingTimeInSec { get; set; }
        public Nullable<int> UnloadingTimeInSec { get; set; }
        public Nullable<long> ContractorOwnerID { get; set; }
        public Nullable<long> CustomerOwnerID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<int> TransporterSource { get; set; }
        public Nullable<bool> ElmStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public Nullable<System.Guid> permitNo { get; set; }
        public string ELM_transporterBrand { get; set; }
        public string ELM_transporterProductionYear { get; set; }
        public string OwnerFullNameAR { get; set; }
        public string OwnerIDType { get; set; }
        public string OwnerIDValue { get; set; }
        public string OwnerMobileNumber { get; set; }
        public string PermitVersion { get; set; }
        public string PermitIssue { get; set; }
        public Nullable<System.DateTime> PermitExpiration { get; set; }
        public bool IsFreeSewer { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Branch Branch2 { get; set; }
        public virtual Landmark Landmark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_ContractStationViolation> NWC_ContractStationViolation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_EventWorkOrder> NWC_EventWorkOrder { get; set; }
        public virtual NWC_ServiceType NWC_ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_VehicleAccessory> NWC_VehicleAccessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_VehicleCustomerLocationClass> NWC_VehicleCustomerLocationClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit> Permit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter_Staff> Transporter_Staff { get; set; }
        public virtual TransporterBrand TransporterBrand1 { get; set; }
        public virtual TransporterManufacturer TransporterManufacturer1 { get; set; }
        public virtual TransporterProductionYear TransporterProductionYear1 { get; set; }
        public virtual TransporterStatus TransporterStatus { get; set; }
        public virtual TransporterType TransporterType1 { get; set; }
    }
}
