//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransporterType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransporterType()
        {
            this.NWC_RestrictedZoneVehicleType = new HashSet<NWC_RestrictedZoneVehicleType>();
            this.Transporter = new HashSet<Transporter>();
        }
    
        public System.Guid ID { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public Nullable<System.Guid> transporterType1 { get; set; }
        public string icon { get; set; }
        public bool isDefault { get; set; }
        public Nullable<bool> isChanged { get; set; }
        public Nullable<bool> isActive { get; set; }
        public System.Guid createdBy { get; set; }
        public System.DateTime creationTime { get; set; }
        public Nullable<System.Guid> skeletonID { get; set; }
        public Nullable<System.Guid> staffRule { get; set; }
        public short Category { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<double> TankCapacity { get; set; }
        public Nullable<double> FuelCalibrationConst_A { get; set; }
        public Nullable<double> FuelCalibrationConst_B { get; set; }
        public Nullable<double> FuelCalibrationConst_C { get; set; }
        public Nullable<double> FuelCalibrationConst_D { get; set; }
        public string NameAr { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public Nullable<long> ExternalSystemId { get; set; }
        public Nullable<System.Guid> SubID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_RestrictedZoneVehicleType> NWC_RestrictedZoneVehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transporter> Transporter { get; set; }
    }
}
