//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractTariff
    {
        public long ID { get; set; }
        public long ContractID { get; set; }
        public System.Guid StationID { get; set; }
        public string StationName { get; set; }
        public Nullable<long> ZoneID { get; set; }
        public string Zone { get; set; }
        public int CustomerLocationClassID { get; set; }
        public string CustomerClassAr { get; set; }
        public string CustomerClassEn { get; set; }
        public int ServiceTypeID { get; set; }
        public string ServiceTypeAr { get; set; }
        public string ServiceTypeEn { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public decimal CubicMeterCharge { get; set; }
        public decimal DistanceCharge { get; set; }
        public decimal AfterFirstKM { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<bool> CotractIsDeleted { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TanckerCapacityId { get; set; }
        public Nullable<long> DateFromHijri { get; set; }
        public Nullable<long> DateToHijri { get; set; }
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
    }
}
