//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_CustomerAccount
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public string AccountId_Integration { get; set; }
        public bool IsDeleted { get; set; }
        public string CustomerName { get; set; }
        public string CustomerIdNumber { get; set; }
        public string CustomerMobile { get; set; }
        public System.Guid CustomerSubId { get; set; }
        public string CustomerLocationAddress { get; set; }
        public int CustomerLocationStatusId { get; set; }
        public string ServiceTypeAr { get; set; }
        public string ServiceTypeEn { get; set; }
    }
}
