//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_PrintCustomerInvoice
    {
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerAddress { get; set; }
        public string OrderNumber { get; set; }
        public int OrderQuantity { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public string EncryptedConfirmationCode { get; set; }
        public decimal NetCost { get; set; }
        public string InvoiceNo { get; set; }
        public string NWC_ZoneName { get; set; }
        public string ContractorFullName { get; set; }
        public string TaxNumber { get; set; }
        public string CompanyAddress { get; set; }
        public System.Guid assignedStationID { get; set; }
        public string StationName { get; set; }
        public string plateNo { get; set; }
        public System.Guid VehicleID { get; set; }
        public long OrderId { get; set; }
        public string TransporterCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
    }
}
