//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_OrdersPerZone
    {
        public long WorkOrderID { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public string CityName { get; set; }
        public string StationName { get; set; }
        public System.Guid StationID { get; set; }
        public System.Guid SubId { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
