//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_TankersPermissionsStatus
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string PlateNo { get; set; }
        public string licenseNo { get; set; }
        public System.Guid StationID { get; set; }
        public string StationName { get; set; }
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> licenseExpiryDate { get; set; }
        public Nullable<System.DateTime> PermissionExpiryDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid SubId { get; set; }
    }
}
