//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_CustomerAccountZone
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public string AccountId_Integration { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public bool IsDeleted { get; set; }
        public string ServiceTypeAr { get; set; }
        public string ServiceTypeEn { get; set; }
        public string CustomerLocationCode { get; set; }
        public int CustomerLocationPriorityID { get; set; }
        public int CustomerLocationCategoryID { get; set; }
        public string CustomerLocationAddress { get; set; }
        public int CustomerLocationStatusId { get; set; }
        public int CustomerLocationClassId { get; set; }
        public string CustomerLocationClassAr { get; set; }
        public string CustomerLocationClassEn { get; set; }
        public long CustomerLocationZoneId { get; set; }
        public string ZoneName { get; set; }
    }
}
