//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_StationServiceTimeSummary
    {
        public long WorkOrderID { get; set; }
        public int OrderQuantity { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.DateTime RequestTime { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public string City { get; set; }
        public System.Guid CityID { get; set; }
        public string StationName { get; set; }
        public System.Guid StationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid SubId { get; set; }
        public Nullable<int> CreateToDeliveredTotalTime { get; set; }
        public Nullable<int> CreateToOutTotalTime { get; set; }
        public Nullable<int> OutToDeliveredTotalTime { get; set; }
    }
}
