//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_CustomerAccountCity
    {
        public long ZoneID { get; set; }
        public System.Guid CityID { get; set; }
        public string CISDivision { get; set; }
        public long ID { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public string AccountId_Integration { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public Nullable<System.DateTime> EligibleStartDate { get; set; }
        public Nullable<System.DateTime> EligibleEndDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IDNumber { get; set; }
    }
}
