//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_StateVehicle
    {
        public System.Guid VehicleID { get; set; }
        public string VehicleCode { get; set; }
        public string VehiclePlateNo { get; set; }
        public Nullable<int> VehicleStatusId { get; set; }
        public string VehicleStatusName { get; set; }
        public string VehicleStatusNameAr { get; set; }
        public string VehicleStatusColorCode { get; set; }
        public Nullable<System.Guid> DriverId { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverMiddleName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverMobile { get; set; }
        public string DriverCode { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<System.Guid> branch { get; set; }
        public Nullable<int> serviceTypeId { get; set; }
        public Nullable<System.Guid> landmark { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> CitySettingsShowInvoice { get; set; }
        public Nullable<bool> CitySettings_ShowCustomerClassEntryGate { get; set; }
        public string VehicleCustomerLocationClassesIds { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public string PermitStatus { get; set; }
    }
}
