//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractWorkOrderAccessory
    {
        public long WorkOrderID { get; set; }
        public long ContractID { get; set; }
        public System.Guid StationID { get; set; }
        public int AccessoryID { get; set; }
        public decimal Charge { get; set; }
    }
}
