//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractList
    {
        public System.Guid SubID { get; set; }
        public long ID { get; set; }
        public string Code { get; set; }
        public long ContractorID { get; set; }
        public string ContractorFullName { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public string ContractTypeEn { get; set; }
        public string ContractTypeAr { get; set; }
        public string ConfirmationNo { get; set; }
        public string AwardLetterNo { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public Nullable<int> ContractStatusID { get; set; }
        public string ContractStatusEn { get; set; }
        public string ContractStatusAr { get; set; }
        public Nullable<int> ContractStatusEnumId { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> StationsCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> TerminationReasonID { get; set; }
    }
}
