//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_SoqyaSchedule
    {
        public long CustomerAccountId { get; set; }
        public string AccountId_Integration { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public string CustomerName { get; set; }
        public int CustomerIdTypeId { get; set; }
        public string CustomerIdNumber { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerLocationAddress { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CancelledSum { get; set; }
        public Nullable<int> DeliveredSum { get; set; }
        public Nullable<int> NotDeliveredSum { get; set; }
        public Nullable<int> ScheduledSum { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
