//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_WorkOrderLogs
    {
        public long WorkOrderId { get; set; }
        public int ActionLogTypeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusComment { get; set; }
        public Nullable<int> DeassignReasonID { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public long CustomerLocationID { get; set; }
        public int ServiceTypeID { get; set; }
        public Nullable<decimal> NetCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<System.Guid> VehicleID { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public Nullable<int> VehicleStatusID { get; set; }
        public string ActionLogTypeAr { get; set; }
        public string ActionLogTypeEn { get; set; }
        public string VehicleStatusAr { get; set; }
        public string VehicleStatusEn { get; set; }
        public string ServiceTypeAr { get; set; }
        public string ServiceTypeEn { get; set; }
        public string WOStatusAr { get; set; }
        public string WOStatusEn { get; set; }
        public string WOStatusReasonAr { get; set; }
        public string WOStatusReasonEn { get; set; }
        public string VehicleCodePlateNo { get; set; }
        public string ChangedByName { get; set; }
        public Nullable<System.DateTime> ScheduledDeliveryTime { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public string DriverName { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public string StationName { get; set; }
        public string CustomerAddress { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.Guid CityID { get; set; }
        public string cityName { get; set; }
        public string ReasonAr { get; set; }
        public string ReasonEn { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
    }
}
