//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ChangesLogsLocationData
    {
        public long EventOrderID { get; set; }
        public Nullable<long> ParentWorkOrderID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public string ServiceTypeEn { get; set; }
        public string ServiceTypeAr { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public string StationName { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public string CustomerAddress { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.Guid CityID { get; set; }
        public string cityName { get; set; }
    }
}
