//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ViolationsApprovalsLogs
    {
        public long ID { get; set; }
        public Nullable<int> DecisionType { get; set; }
        public long ViolationID { get; set; }
        public int LevelID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long ContractTermId { get; set; }
        public string ViolationTicketNumber { get; set; }
        public string ViolationLocation { get; set; }
        public decimal TotalPenalty { get; set; }
        public System.DateTime IncidentTime { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public string VehicleCode { get; set; }
        public string VehiclePlateNo { get; set; }
        public string ViolationDescription { get; set; }
        public string ContractTermCode { get; set; }
        public string ContractTermDescription { get; set; }
        public string ContractTermName { get; set; }
        public Nullable<long> ContractID { get; set; }
        public Nullable<System.Guid> DriverId { get; set; }
        public int PaymentStatusId { get; set; }
        public string PaymentStatusAr { get; set; }
        public string PaymentStatusEn { get; set; }
        public string CreatedByFirstName { get; set; }
        public string CreatedByMiddleName { get; set; }
        public string CreatedByLastName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
