//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_BranchSetting
    {
        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public bool IsSubBranch { get; set; }
        public System.Guid SubId { get; set; }
        public Nullable<bool> ShowPrice { get; set; }
        public Nullable<bool> ShowInvoice { get; set; }
        public Nullable<int> TankerQuotaNo { get; set; }
        public Nullable<bool> ShowCustomerClassEntryGate { get; set; }
        public Nullable<int> AutoCancelationNewOrdersHours { get; set; }
        public Nullable<int> AutoCancelationOnHoldOrdersHours { get; set; }
        public Nullable<bool> ValidateConfermationCode { get; set; }
        public Nullable<bool> RequiresPayment { get; set; }
        public Nullable<int> ApprovalLevelsCount { get; set; }
        public Nullable<bool> ValidationApprovalRequired { get; set; }
    }
}
