//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractStations
    {
        public long contractStationID { get; set; }
        public bool ContractStationIsDeleted { get; set; }
        public System.Guid StationID { get; set; }
        public long ContractID { get; set; }
        public Nullable<long> ContactPersonID { get; set; }
        public string stationName { get; set; }
        public string stationCode { get; set; }
        public Nullable<bool> stationIsDeleted { get; set; }
        public Nullable<System.Guid> branchId { get; set; }
        public System.Guid SubId { get; set; }
        public Nullable<System.Guid> AreaID { get; set; }
        public string BranchName { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string LandlineNumber { get; set; }
        public string LandlineNumbeCode { get; set; }
        public string MobileCode { get; set; }
        public string Email { get; set; }
        public string PersonAddress { get; set; }
        public string PersonAddressPostalCode { get; set; }
        public string Position { get; set; }
        public Nullable<int> PersonalIDType { get; set; }
        public string PersonalIDNumber { get; set; }
    }
}
