//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_VehicleViolation
    {
        public long Id { get; set; }
        public string ViolationTicketNumber { get; set; }
        public System.DateTime IncidentTime { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int PaymentStatusId { get; set; }
        public string TermName { get; set; }
        public string TermCode { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
        public string ViolationPaymentStatusAr { get; set; }
        public string ViolationPaymentStatusEn { get; set; }
        public decimal TotalPenalty { get; set; }
    }
}
