//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_AssignableVehicles
    {
        public System.Guid ID { get; set; }
        public string VehicleCodePlateNo { get; set; }
        public Nullable<int> VehicleStatusId { get; set; }
        public string VehicleStatusName { get; set; }
        public string VehicleStatusNameAr { get; set; }
        public Nullable<int> Capacity { get; set; }
        public System.Guid DriverID { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNumber { get; set; }
        public string DriverCode { get; set; }
        public long ZoneID { get; set; }
    }
}
