//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_WorkOrderVehicle
    {
        public Nullable<System.Guid> VehicleID { get; set; }
        public long WorkOrderID { get; set; }
        public string OrderNumber { get; set; }
        public decimal TotalCost { get; set; }
        public string TransporterCode { get; set; }
        public string TransporterPlateNo { get; set; }
        public Nullable<int> VehicleStatusID { get; set; }
        public string VehicleStatusName { get; set; }
        public string VehicleStatusNameAr { get; set; }
        public string VehicleStatusColorCode { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverMiddleName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverMobileNumber { get; set; }
        public string DriverCode { get; set; }
        public int LastStatusID { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public System.Guid AssignedStationID { get; set; }
        public Nullable<System.DateTime> orderCreateTime { get; set; }
        public Nullable<System.DateTime> orderLastStatusTime { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<bool> CitySettings_ShowInvoice { get; set; }
        public Nullable<bool> TransporterIsDeleted { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<bool> CitySettings_ShowCustomerClassEntryGate { get; set; }
        public string VehicleCustomerLocationClassesIds { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public string PermitStatus { get; set; }
    }
}
