//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_DeviceMeterReading
    {
        public long ID { get; set; }
        public long DeviceMeterID { get; set; }
        public decimal MeterReading { get; set; }
        public System.DateTime ReadingTime { get; set; }
        public string ReadingComment { get; set; }
        public bool IsDeleted { get; set; }
        public string ConnectorTubeNumber { get; set; }
        public string MeterSerialNumber { get; set; }
        public string ManholeNumber { get; set; }
        public Nullable<bool> IsScadaAutoReading { get; set; }
        public int ServiceTypeID { get; set; }
        public System.Guid SubID { get; set; }
        public System.Guid StationID { get; set; }
        public string StationName { get; set; }
        public string StationCode { get; set; }
    }
}
