//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_VehiclePerformance
    {
        public System.Guid SubID { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string Code { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public string EN_StatusName { get; set; }
        public string AR_StatusName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public System.Guid StationId { get; set; }
        public string StationName { get; set; }
        public System.Guid SubBranchId { get; set; }
        public string SubBranchName { get; set; }
        public System.Guid BranchId { get; set; }
        public string BranchName { get; set; }
        public string DriverNames { get; set; }
        public Nullable<int> TotalExitTripsCount { get; set; }
        public Nullable<int> TotalDeliveredOrdersCount { get; set; }
        public Nullable<int> ResidentialDeliveredOrdersCount { get; set; }
        public Nullable<int> CommercialDeliveredOrdersCount { get; set; }
        public Nullable<int> ViolationsCount { get; set; }
        public Nullable<int> PaidViolationsCount { get; set; }
        public Nullable<int> UnPaidViolationsCount { get; set; }
        public Nullable<int> PartiallyPaidViolationsCount { get; set; }
        public int TotalOrdersCount { get; set; }
        public int ClosedByCodeOrdersCount { get; set; }
        public decimal ClosedByCodeOrdersPercentage { get; set; }
    }
}
