//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_SoqyaScheduledQuantities
    {
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public long CustomerAccountId { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
        public System.Guid StationID { get; set; }
        public bool StationIsMain { get; set; }
        public string name { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
    }
}
