//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractPriceList
    {
        public string StationName { get; set; }
        public System.Guid StationID { get; set; }
        public long ContractID { get; set; }
        public long ContractPriceID { get; set; }
        public string ServiceTypeNameAr { get; set; }
        public string ServiceTypeNameEn { get; set; }
        public string CustomerLocationClassNameEn { get; set; }
        public string CustomerLocationClassNameAr { get; set; }
        public decimal PriceCharge { get; set; }
        public bool ContractPriceIsDeleted { get; set; }
    }
}
