//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_PrintVehicleInvoice
    {
        public System.Guid VehicleId { get; set; }
        public string VehicleCode { get; set; }
        public string VehiclePlateNo { get; set; }
        public Nullable<int> VehicleCapacity { get; set; }
        public System.Guid VehicleSubId { get; set; }
        public Nullable<int> VehicleServiceTypeID { get; set; }
        public Nullable<System.Guid> StationId { get; set; }
        public string StationName { get; set; }
        public Nullable<bool> ContractStationsIsActive { get; set; }
        public bool ContractStationsIsDeleted { get; set; }
        public string ContractCode { get; set; }
        public long ContractorID { get; set; }
        public string ContractorCode { get; set; }
        public string ContractorFullName { get; set; }
        public string ContractorTaxNumber { get; set; }
        public string ContractorAddress { get; set; }
        public int CustomerLocationClassID { get; set; }
        public string SubContractorFullName { get; set; }
        public string SubContTaxNumber { get; set; }
        public string SubContCompanyAddress { get; set; }
    }
}
