//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_WorkOrderBasicDetails
    {
        public long OrderId { get; set; }
        public string OrderNumber { get; set; }
        public string StatusNameEn { get; set; }
        public string StatusNameAr { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<System.DateTime> OrderPlacedOn { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerAddress { get; set; }
        public decimal TotalCost { get; set; }
        public int OrderQuantity { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public System.Guid StationID { get; set; }
        public Nullable<decimal> StationLat { get; set; }
        public Nullable<decimal> StationLng { get; set; }
        public string StationName { get; set; }
        public bool IsVirtualStation { get; set; }
        public string ServiceTypeEn { get; set; }
        public string ServiceTypeAr { get; set; }
        public string TankerPlateNo { get; set; }
        public string VehicleCodePlateNo { get; set; }
        public Nullable<int> VehicleCapacity { get; set; }
        public Nullable<int> VehicleCapacityUnit { get; set; }
        public string VehicleStatusName { get; set; }
        public string vehicleStatusNameAr { get; set; }
        public string DriverName { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<System.Guid> AssignedDriverID { get; set; }
        public System.Guid AssignedStationID { get; set; }
        public Nullable<System.Guid> AssignedVehicleID { get; set; }
        public string ConfirmationCode { get; set; }
        public long CustomerLocationId { get; set; }
        public int ServiceTypeId { get; set; }
        public long CustomerId { get; set; }
        public long ZoneID { get; set; }
        public Nullable<double> customerLocationLat { get; set; }
        public Nullable<double> customerLocationLng { get; set; }
        public string RouteLatLngString { get; set; }
        public int LastStatusID { get; set; }
        public Nullable<System.DateTime> LastStatusTime { get; set; }
        public string LastStatusReason { get; set; }
        public Nullable<System.DateTime> LastStatusTimeVehicle { get; set; }
        public string WorkOrderInvoiceStatusNameAr { get; set; }
        public string WorkOrderInvoiceStatusNameEn { get; set; }
        public string Area { get; set; }
        public string CityName { get; set; }
        public string ZoneName { get; set; }
        public decimal CostBeforVAT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public decimal CostAfterVAT { get; set; }
        public string PaymentStatusAr { get; set; }
        public string PaymentStatusEn { get; set; }
        public int CustomerIdTypeId { get; set; }
        public string CustomerIdNumber { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public string DriverMobileNumber { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
