//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractTerms
    {
        public long ID { get; set; }
        public string ContractTermCode { get; set; }
        public string ContractTermName { get; set; }
        public string Description { get; set; }
        public Nullable<long> TermsCategoryID { get; set; }
        public long ContractID { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public bool ContractTermIsDeleted { get; set; }
        public string stationName { get; set; }
        public Nullable<bool> stationIsDeleted { get; set; }
        public Nullable<System.Guid> stationSubId { get; set; }
        public string stationCode { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
        public Nullable<System.Guid> TermsCategorySubID { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> TotalValueUnitId { get; set; }
        public string TotalValueUnitNameAr { get; set; }
        public string TotalValueUnitNameEn { get; set; }
    }
}
