//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ZoneList
    {
        public long Id { get; set; }
        public System.Guid CityID { get; set; }
        public string Code { get; set; }
        public string ZoneName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid SubID { get; set; }
        public string CityName { get; set; }
        public string MainStationName { get; set; }
        public Nullable<System.Guid> MainStationId { get; set; }
        public string MainStationCode { get; set; }
        public Nullable<int> CountOfBackupStations { get; set; }
        public Nullable<int> RestrictedZoneVehicleTypes { get; set; }
    }
}
