//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_UserLandmarkPermission
    {
        public System.Guid StaffID { get; set; }
        public string FullName { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ListofLandmarks { get; set; }
        public string ListofServices { get; set; }
    }
}
