//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_WorkOrderList
    {
        public System.Guid SubID { get; set; }
        public long WorkOrderID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public System.DateTime ScheduledDeliveryTime { get; set; }
        public int OrderQuantity { get; set; }
        public int ServiceTypeID { get; set; }
        public string ServiceTypeEN { get; set; }
        public string ServiceTypeAR { get; set; }
        public long CustomerLocationID { get; set; }
        public string AccessoriesAr { get; set; }
        public string AccessoriesEn { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string ConfirmationCode { get; set; }
        public string LastStatusReason { get; set; }
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerAddress { get; set; }
        public int ClassID { get; set; }
        public string ClassNameEn { get; set; }
        public string ClassNameAr { get; set; }
        public int PriorityID { get; set; }
        public string PriorityNameEn { get; set; }
        public string PriorityNameAr { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public string CityName { get; set; }
        public System.Guid AssignedStationID { get; set; }
        public System.Guid LandmarkID { get; set; }
        public string StationName { get; set; }
        public Nullable<System.Guid> AssignedVehicleID { get; set; }
        public string VehicleCodePlateNo { get; set; }
        public Nullable<int> vehicleCapacity { get; set; }
        public Nullable<int> vehicleCapacityUnit { get; set; }
        public string vehiclestatusName { get; set; }
        public string vehiclestatusNameAr { get; set; }
        public Nullable<System.DateTime> LastStatusTimeVehicle { get; set; }
        public Nullable<System.Guid> AssignedDriverID { get; set; }
        public string DriverName { get; set; }
        public string DriverMobileNumber { get; set; }
        public string DriverCode { get; set; }
        public Nullable<System.Guid> DriverID { get; set; }
        public int LastStatusID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string LastStatusNameEn { get; set; }
        public string LastStatusNameAr { get; set; }
        public Nullable<System.Guid> LastStatusBy { get; set; }
        public string LastStatusByUserName { get; set; }
        public Nullable<System.DateTime> LastStatusTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string TankerPlateNo { get; set; }
        public string StatusColor { get; set; }
        public Nullable<int> AssignRetrials { get; set; }
        public Nullable<System.DateTime> AssignRetrialTime { get; set; }
        public Nullable<int> CancelRetrials { get; set; }
        public Nullable<System.DateTime> CancelRetrialTime { get; set; }
        public Nullable<double> CustomerLocationLat { get; set; }
        public Nullable<double> CustomerLocationLng { get; set; }
        public decimal CostBeforVAT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public decimal CostAfterVAT { get; set; }
        public string PaymentStatusAr { get; set; }
        public string PaymentStatusEn { get; set; }
        public int CustomerIdTypeId { get; set; }
        public string CustomerIdNumber { get; set; }
        public string CustomerMobile { get; set; }
        public Nullable<long> CustomerAccountId { get; set; }
        public string SourceApplication { get; set; }
        public decimal TotalCost { get; set; }
        public Nullable<bool> ZoneWithoutTanker { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryAr { get; set; }
        public string CategoryEn { get; set; }
        public bool IsVirtualStation { get; set; }
        public Nullable<bool> ClosedByCode { get; set; }
    }
}
