//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_LandmarkNWCSettings
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid AreaId { get; set; }
        public string AreaName { get; set; }
        public System.Guid CityId { get; set; }
        public string CityName { get; set; }
        public string CustomerClasses { get; set; }
        public string EN_CustomerClassNames { get; set; }
        public string AR_CustomerClassNames { get; set; }
        public string StationServices { get; set; }
        public string EN_StationServiceNames { get; set; }
        public string AR_StationServiceNames { get; set; }
        public System.Guid SubId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string EN_StatusName { get; set; }
        public string AR_StatusName { get; set; }
        public bool IsVirtual { get; set; }
        public string StationDefaultList { get; set; }
    }
}
