//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_Report_DailyOrderSummary
    {
        public int ServiceTypeID { get; set; }
        public string ServiceTypeEN { get; set; }
        public string ServiceTypeAR { get; set; }
        public System.Guid StationID { get; set; }
        public string StationName { get; set; }
        public string StationCode { get; set; }
        public System.Guid StationSubId { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<int> TotalSum { get; set; }
        public Nullable<int> FailedToDeliverCount { get; set; }
        public Nullable<int> FailedToDeliverSum { get; set; }
        public Nullable<int> DeliveredCount { get; set; }
        public Nullable<int> DeliveredSum { get; set; }
        public Nullable<int> CancelledCount { get; set; }
        public Nullable<int> CancelledSum { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
