//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_AvailableTankerSizes
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> Landmark { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<bool> ShowPrice { get; set; }
        public int CustomerLocationClassID { get; set; }
    }
}
