//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_VehicleNWCSettings
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string plateNo { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ListofAccessory { get; set; }
        public string ListofClass { get; set; }
        public Nullable<System.Guid> StationID { get; set; }
        public string name { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<System.Guid> transporterType { get; set; }
        public string transporterTypeName { get; set; }
        public string transporterTypeNameAr { get; set; }
    }
}
