//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ChangesLogs
    {
        public long EventOrderID { get; set; }
        public Nullable<long> ParentWorkOrderID { get; set; }
        public long EventID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int EventTypeID { get; set; }
        public string StatusComment { get; set; }
        public Nullable<int> DeassignReasonID { get; set; }
        public string ReasonAr { get; set; }
        public string ReasonEn { get; set; }
        public int StatusID { get; set; }
        public string StatusEn { get; set; }
        public string StatusAr { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<System.DateTime> ScheduledDeliveryTime { get; set; }
        public Nullable<long> CustomerLocationID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public string AccessoriesEn { get; set; }
        public string AccessoriesAr { get; set; }
    }
}
