//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_ContractAccessory
    {
        public long ID { get; set; }
        public long ContractID { get; set; }
        public System.Guid StationID { get; set; }
        public int AccessoryID { get; set; }
        public string AccessoryNameAr { get; set; }
        public string AccessoryNameEn { get; set; }
        public decimal Charge { get; set; }
        public Nullable<int> ContractStatusID { get; set; }
        public string StationName { get; set; }
        public System.Guid SubID { get; set; }
        public Nullable<bool> IsContractDeleted { get; set; }
        public bool IsDeleted { get; set; }
        public int ContractStatusEnumId { get; set; }
    }
}
