//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NWC_SoqyaSchedule
    {
        public long Id { get; set; }
        public bool IsDeleted { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> TimeSlotFrom { get; set; }
        public Nullable<System.TimeSpan> TimeSlotTo { get; set; }
        public long CustomerAccountId { get; set; }
        public Nullable<int> SoqyaBalance { get; set; }
        public long CustomerId { get; set; }
        public long CustomerLocationId { get; set; }
        public string CustomerName { get; set; }
        public int CustomerIdTypeId { get; set; }
        public string CustomerIdNumber { get; set; }
        public string CustomerMobile { get; set; }
        public string CustomerLocationAddress { get; set; }
        public long ZoneID { get; set; }
        public string ZoneName { get; set; }
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<long> WorkOrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> LastStatusID { get; set; }
        public string LastStatusNameEn { get; set; }
        public string LastStatusNameAr { get; set; }
        public string StatusColor { get; set; }
        public string AccountId_Integration { get; set; }
        public Nullable<bool> IsGenerated { get; set; }
    }
}
