//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.DAL.NWCEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_permitList
    {
        public System.Guid ID { get; set; }
        public System.Guid AreaId { get; set; }
        public string Area { get; set; }
        public System.Guid CityId { get; set; }
        public string City { get; set; }
        public string Station { get; set; }
        public System.Guid stationId { get; set; }
        public string DriverID { get; set; }
        public string DriverMobile { get; set; }
        public string TankerNumber { get; set; }
        public Nullable<System.DateTime> Expirationdate { get; set; }
        public string Availabletimefrom { get; set; }
        public string Availabletimeto { get; set; }
        public Nullable<int> PermitStatus { get; set; }
        public string code { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<System.Guid> TransporterID { get; set; }
    }
}
