export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Save': 'Save',
  'Cancel': 'Cancel',
  'Next': 'Next',
  'IdNo': 'ID',
  'Searchexisting': 'Search for existing guardian',
  'IdNoReq': 'Please Enter Search for existing guardian',
  'Relation': 'Relation',
  'RelationReq': 'Please Select Realtion',
  'MainContact': 'Main contact',
  'Code': 'Code',
  'CodeReq': 'Please Enter Plan ID',
  'GuardianName': 'Guardian Name',
  'FirstName': 'First Name',
  'LastName': 'Middle Name',
  'FamilyName': 'Last Name',
  'GuardianNameReq': 'Please Enter Guardian Name',
  'GuardianManage': 'Guardian Management',
  'IdType': 'Id Type',
  'IdTypeReq': 'Please Select Id Type',
  'ExpDate': 'ID Expiration Date ',
  'SelectExpDate': 'Select ID Expiration Date ',
  'ExpDateReq': 'Please Enter Expire Date',
  'MobNo1': 'Prime Mobile ',
  'MobNoreq': 'Please Enter Mobile Number',
  'MobNo2': 'Second Mobile ',
  'EnterMobNo': 'Mobile Number ',
  'LandNo': 'Landline Phone ',
  'EnterLandNo': 'Enter Landline Phone ',
  'Occupation': 'Title',
  'PresentAddress': 'Home Address',
  'EnterPresentAddress': 'Enter full address (e.g. building No, street, Area, City, Country) ',
  'PresentAddressReq': 'Please Enter Current Address',
  'WorkNo': 'Work Landline Phone',
  'EnterWorkNo': 'Work Landline Phone',
  'WorkAddress': 'Work Address',
  'Email': 'Email',
  'EmailReq': 'Please Enter Email',
  'EmailInvalid': 'Invalid Email',
  'UserName': 'User Name',
  'UserNameReq': 'Please Enter User Name',
  'Password': 'Password',
  'PasswordReq': 'Please Enter Password',
  'PasswordPattern': 'Password must be at least 6 up to 12 Capital and small chars, numbers and special chars',
  'ConfirmPassword': 'Confirm Password',
  'ConfirmPasswordReq': 'Please Enter Confirm Password',
  'ConfirmPasswordNotMatch': 'The confirmed password is not matched',

  'Attachments': 'Attachments',
  // page plan details
  'PlanName': 'Plan Name',
  'Description': 'Description',
  'MaxTripTime': 'Max Trip Time mins ',
  'WaitingTime': 'Waiting Time mins ',
  'Type': 'Plan Type',
  'StartTime': 'Trips starts at',
  'EndTime': 'Trip Ends at',
  'StartDate': 'Start Date',
  'EndDate': 'End Date',
  'Days': 'Days',
  'BasicDetails': 'Basic Details',
  'PlanExecutionRange': 'Plan Execution Range',
  'WaitingTimeMustByMoreThanZero': 'Waiting time must be greater than zero',
  'MaxTripTimeMustByMoreThanZero': 'max trip time must be greater than zero',
  'AtLeastOneDayRequired': 'select days',

  'NotStarted': 'Not Started',
  'InProgress': 'Inprogress',
  // page plan  students buses
  'Branch': 'Branch',
  'SubBranch': 'Sub Branch',
  'StudentName': 'Student Name',
  'StudentSelected': 'Student Selected',
  'Search': 'Search',
  'Busses': 'Busses',
  'Selected': 'Selected',
  'GenerateTrips': 'Generate Trips',
  'Back': 'Back',
  'useanunifed': 'Apply to all buses',
  'students': 'Students',
  'occurance': 'Weekly Occurrence',
  'plannedstudent': 'No of allocated students',
  'plateNo': 'plate No',
  'TotalMielage': 'Total mileage',
  'Duration': 'Duration',
  'SelectName': 'Select name | Plan ID ',
  'Update': 'Update',
  'code': 'Plan ID',
  'Planed': 'Planned',
  'PlanedTime': 'Planned Time',

  'Actuals': 'Actual Time',
  'Play': 'Play',
  'tripmonitoring': 'Trip Monitoring',
  // plan list
  'PlanCode': 'Plan ID',
  'NewPlan': 'Add New Plan ',
  'PlanType': 'Plan Type',
  'Trips': 'Trips',
  'SelectPlan': 'Select Plan Name ',
  'SelectPlanType ': 'Select Plan Type ',
  'SelectPlanCode': 'Select Plan ID ',
  'PlanList': ' Plans List',
  'TripsList': 'Trips List',
  'PikeDate': 'Pike Date',
  'BusCode': 'Bus Code',
  'PlateNumber': 'Bus Plate Number',
  'DriverName': 'Driver',
  'SupervisorName': 'Supervisor',
  'SelectSupervisor': 'Select supervisor name | code ',
  'SelectDriver': 'Select driver name | code ',
  'PlannedTime': 'Planned Time',
  'ActualTime': 'Actual Time',
  'PlannedStudents': 'No of allocated students',
  'ActualStudents': 'Actual Students',
  'Status': 'Status',
  'TripStatus': 'Trip Status',
  'NoTripsShow': 'No Trips to show',
  'tripdetails': 'Trip Details',
  'showtrips': 'Show Daily Trips',
  'ActiveInactive ': 'Active/ Inactive ',
  'Name': 'Name',
  'From': 'From',
  'Reset': 'Clear ',
  'itemsin': 'Items in',
  'PlannedTrips': 'Planned Trips',
  'page': 'Page',
  'Plannedfrom': 'Planned From',
  'Plannedto': 'Planned To',
  'Actualfrom': 'Actual From',
  'Actualto': 'Actual To',
  'VehicleCodePlateNumber': 'Bus',

  'ArrivalTime': 'Arrival Time',
  'Planning': 'Planning',
  'messagevalidationplandate': 'Start Date must be before End Date',
  'messagevalidationplantime': 'Arrival time must be after Start Time',
  // page plan details

  'tripstatus': 'Trip Status',
  'plannedTripId': 'Planned Trip ID',
  'EnterDetails': 'Enter Details',
  'StudentAndBus': 'Students and Buses',
  'generatedtrips': 'Generate Trips',
  'GeneratedTrip' : 'Generated Trip',
  'Crew': 'Crew',
  'SupervisourName': 'Supervisor',
  'AssignedCrew': 'Assigned Crew',
  'AssignedVeicle': 'Assigned Bus',
  'BusNumberPlate': 'Bus',
  'SelectBus': 'Select Bus',
  'SelectBusTripDetails': 'Select plate no. | code ',

  'PlanDate': 'Planned Date',
  'PlanTime': 'Planned Time',
  'PlanMielage': 'Planned Mileage',
  'PlanStudents': 'No of allocated students',
  'Pickup': 'Pickup',
  'PickupLocation': 'Pick-up Location',
  'DropOffLocation': 'Drop-off Location',
  'Dropoff': 'Drop off',
  'PlanTripDuration': 'Planned Trip Duration',
  'ActualDate': 'Actual Date',

  'ActualMielage': 'Actual Mileage',
  'ActualTripDuration': 'Actual Trip Duration',
  'BusNo': 'Bus No',
  'MissedBuss': 'No Show',
  'inBus': 'Onboard',
  'WaitintgPickUp': 'Waitintg Pickup',
  'Absent': 'Absent',
  'Active': 'Active',
  'pause': 'Pause',
  'replay': 'Re-play',
  'missed': 'No Show',
  'absent': 'absent',
  'onboard': 'On Board',
  'Delete': 'Delete',
  'Dropped': 'Dropped',
  'Completed': 'Completed',
  'Failed': 'Failed',
  'Cancelled': 'Cancelled',
  'hold': 'hold',
  //shared
  'InputRequired': 'Please Enter',
  'DropRequired': 'Please Select',
  'GeneralError': 'Something went wrong, please try again later. If the problem continues please check with your system administrator',
  'EmailExist': 'Email Already Exist',
  'UserNameExist': 'User Name Already Exist',
  'IdExist': 'Identity Number Already Exist',
  'getProfile': 'Get Profile',
  'GuardSaved': 'Guardian information is Saved Successfully',
  'GuardRemoveConstrain': 'unable to delete guardian please delete guardainship with others students',
  'OR': 'OR',
  //menu
  'Resources': 'Resources',
  'Operations': 'Operations',
  'Maintenance': 'Maintenance',
  'GPS': 'Live Tracking',
  'RentCars': 'Rent Vehicles',
  'ManageSchool': 'Smart School Bus',
  'Reports': 'Reports',

  // Shools Tab
  'Sco_PlansManage': 'Plans Management',
  'Sco_StudentsManage': 'Students Management',
  'Sco_TripsManage': 'Trips Management',
  'Sco_LiveDashboard': 'Live Dashboard',
  'Sco_HistoryDashboard': 'History Dashboard',
  // Rent Cars
  'Rent_Dashboard': 'Main Dashboard',
  'Rent_PricePlans': 'Price Plans',
  'Rent_AssignPrice': 'Assign Price Plan to Vehicles',
  'Rent_Promotion': 'Promotion Plans',
  'Rent_AdditionalServices': 'Additional Services',
  'Rent_Customers': 'Customers',
  'Rent_RentVehicle': 'Rent Vehicle',
  'Rent_ReturnVehicle': 'Return Vehicle',
  'Rent_RentContracts': 'Rent Contracts',

  // Reports tab
  'rep_General': 'General Reports',
  'rep_GPS': 'Live Tracking Reports',
  'rep_Maintenance': 'Maintenance Reports',
  'rep_Operations': 'Operations Report',
  'rep_RentCars': 'Car Rental Reports',

  // Gps
  'Gps_LiveTracking': 'Live Tracking',
  'Gps_FleetMonitoring': 'Fleet Monitoring and Live Tracking',
  'Gps_Geofences': 'Geofences',
  'Gps_Group': 'Group Management',

  //Operations
  'oper_Landmarks': 'Landmarks',
  'oper_Routes': 'Routes',
  'oper_WorkOrders': 'Work Orders',
  'oper_Monitor': 'Monitor Work Orders',

  // Resources
  'Res_Dashboard': 'Main Dashboard',
  'Res_Vehicles': 'Vehicles',
  'Res_Staff': 'Staff',
  'Res_Structure': 'Structure and Distribution',

  // Maintenance
  'maint_RFR': 'RFR Management',
  'maint_Accident': 'Accident RFR Management',
  'maint_PM_RFR': 'PM RFR Management',
  'maint_CM_RFR': 'CM RFR Management',
  'maint_WorkOrder': 'Work Order',
  'maint_Vendor': 'Vendor Work Orders List',
  'maint_Preventive': 'Preventive Maintenance',
  'maint_Dashboard': 'Maintenance Dashboard',

  // Student List
  'StudentList': 'Student List',
  'Allocation': 'Allocation',
  'EmergencyContact': 'Emergency Contact',
  'NA': ' N/A',
  'NoResultisfound': 'No Result is found',
  'Guardians': 'Guardians',
  'StdType': 'Type',
  'Grade': 'Grade',
  'Classes': 'Classes',
  'Gender': 'Gender',
  'RFID': 'Personal Identification ( RFID )',
  'BusSubscription': 'Subscribed to a bus ',
  'StudentEmail': "Student's Email",
  'StudentMobile': 'Student Mobile',
  'AdvancedSearch': 'Advanced Search',
  'StudentDetails': 'Student Details',
  'AddNewStudent': 'Add New Student',
  'SelectBranchName': 'Select branch name ',
  'SelectSubBranchName': 'Select sub branch name ',
  // student data

  'Upload': 'Upload',
  'GradeAndClass': 'Grade and Class',
  'DateOfBirth': 'Date of Birth',
  'latitude': 'Latitude',
  'longitude': 'Longitude',

  'NoSubscription': 'Not subscribed to a bus ',
  'StudentEmailID': 'Student Email ID',
  'NotValid': 'not valid',
  'PersonalIdentification': 'Personal Identification',
  'DownloadSample': 'Download Sample',
  'Browse': 'Browse',
  'StudentBulkUpload': 'Student Bulk Upload',
  // generate plan
  'StartLocation': 'Start Location',
  'EndLocation': 'End Location',
  'StartAt': 'Start At',
  'EndAt': 'End At',
  'SeatsReserved': 'Seats Reserved',
  'guardianBulkUpload': 'guardian Bulk Upload',


  'SearchStudentName': "Select Students' Name",
  'SelectAll': 'Select All',
  'UnSelectAll': 'UnSelect All',
  'SelectClass': 'Select Class/s',
  'SelectGender': 'Select Gender',
  'SelectBranch': ' Select Branch/s name/s',
  'SelectSubBranch': 'Select Sub-Branch/s name/s',
  'SelectRFID': "Select Students' RFID",
  'SelectSubscription': "Select Students' Subscription Status",
  'SelectEmail': "Select Students' Email",
  'SelectMobile': "Select  Students' Mobile",
  'SelectGrade': "Select  students' Grade",
  'SelectPlanType': "Select Plan Type",
  'SelectCode': "Select Students' Code",
  'SelectGuardians': "Select Students' Guardians ",
  'EnterStudentEmail': "Enter  Student's  Email ",
  'EnterStudentMobile': "Enter Student's Mobile Number  ",

  'PleaseSelectSubBranch': 'Select Sub Branch',
  'PleaseSelectBranch': 'Select Branch',
  'SelectDateOfBirth': 'Select Date of Birth',
  'EnterCode': "Enter Code",
  'EnterStudentCode': "Enter Student's Code",
  'ReenterPassword': 'Re-enter Password ',

  //Dashboard
  'Dashboard': 'Live Dashboard',
  'vehicle': 'Vehicle',
  'VehivleSearch': 'Select Vehicle | PlatNumber',
  'DestLandMark': 'Dest Landmark',
  'StartLandMark': 'Start Landmark',
  'PlannedStartTime': 'PlannedTrip Start Time',
  'PlannedEndTime': 'PlannedTrip End Time',
  'ActuallStartTime': 'Actuall Trip Start Time',
  'ActuallEndTime': 'Actuall Trip End Time',
  'Time': 'Time',
  'Plan': 'plan',
  'Actual': 'Actual',
  'Route': 'Route',
  'Outside': 'Outside',
  'Onboard': 'Onboard',
  // New Add
  'BusNumber': 'Bus Number',
  'SeatsNumber': 'Seat Number',
  'DestLocation': 'Destination Location',
  'AddNewStudents': 'Add New Student to Trip route :',
  'SelectGrades': 'Select Grade',
  'SelectStudentName': 'Select Student Name',
  'SelectStudentOrderName': 'Select Student order on route',
  'SeatsAvailable': 'Seats Available',
  'Add': 'Add',
  'Source': 'Source',
  'Destination': 'Destination',
  'SelectPlateNo': 'Select Plate No | code',
  'SelectNames': 'Select name',
  'BusPlateNo': 'Bus Plate No.',
  'ExecutionRage': 'Execution Range',
  'Mileage': 'Mileage (Kms)',
  'Durations': 'Duration (Mins)',
  'StudentsNo': 'Students No.',
  'ExecutionTime': 'Execution Time',
  'totaldistance': 'Total Distance',
  'totalduration': 'Total Duration',
  'AvailableSeats': 'Available Seats ',
  'Seats': 'Seats',
  'Mins': 'MINs',
  'Kms': 'KMs',
  'ActualRoute': 'Actual Route',
  'PlannedRoute': 'Planned Route',
  'BusSubscriptions': 'Bus Subscription',
  'AllCategories': 'All Categories',
  'GPS_DashboardKey' : 'Live Traking Dashboard',

  //Permit
  'Permits':'Tanker Permit',

  // Staff List
  'StaffCode': 'Staff Code',
  'StaffList':'Staff List'
};
