export const LANG_AR_NAME = 'ar';

export const LANG_AR_TRANS = {
  'hello': 'مرحباً',
  'IdNoReq': 'من فضلك ادخل الكود الشخصي',


  'InputRequired': 'من فضلك ادخل',
  'DropRequired': 'من فضلك أختر',
  'IdNo': 'الرقم التعريفى',
  'Save': 'حفظ',
  'Cancel': 'ألغاء',
  'Next': 'التالي',
  'Searchexisting': 'ابحث عن ولي أمر محفوظ سابقاً ',
  'Relation': 'علاقة ولي الأمر بالطالب',
  'RelationReq': 'من فضلك قم بأختيارعلاقة ولي الأمر بالطالب',
  'MainContact': 'شخص الاتصال الرئيسي',
  'Code': 'كود ولي الأمر',
  'CodeReq': 'من فضلك قم بأدخال كود ولي الأمر',
  'GuardianName': 'اسم ولي الأمر',
  'FirstName': 'الأسم الأول',
  'LastName': 'الأسم الأوسط',
  'FamilyName': 'أسم العائلة',
  'GuardianNameReq': 'من فضلك قم بأدخال اسم ولي الأمر كاملاً',
  'GuardianManage': 'بيانات ولي الأمر',
  'IdType': 'نوع الهوية',
  'IdTypeReq': 'من فضلك قم بأدخال نوع الهوية',
  'ExpDate': 'تاريخ إنتهاء الهوية',
  'SelectExpDate': ' أختر تاريخ إنتهاء الهوية',
  'ExpDateReq': 'من فضلك قم بأدخال تاريخ إنتهاء الهوية',
  'MobNo1': 'رقم الهاتف المحمول 1',
  'MobNoreq': 'من فضلك قم بأدخال رقم الهاتف',
  'MobNo2': 'رقم الهاتف المحمول 2',
  'EnterMobNo': 'من فضلك قم بأدخال رقم الهاتف',
  'LandNo': 'رقم الهاتف الأرضي',
  'EnterLandNo': 'من فضلك قم بأدخال رقم الهاتف ',
  'Occupation': 'الوظيفة',
  'PresentAddress': 'العنوان الحالي',
  'PresentAddressReq': 'من فضلك قم بأدخال عنوان ولي الأمر الحالي',
  'WorkNo': 'رقم الهاتف بالعمل',
  'WorkAddress': 'عنوان العمل',
  'Email': 'البريد الإلكتروني',
  'EmailReq': ' من فضلك قم بأدخال البريد الإلكتروني',
  'EmailInvalid': 'بريد إلكتروني خطأ',
  'EnterWorkNo': 'من فضلك قم بأدخال رقم الهاتف بالعمل',
  'UserName': 'أسم المستخدم',
  'UserNameReq': 'من فضلك أدخل اسم المستخدم',
  'Password': 'كلمة المرور',
  'PasswordReq': 'من فضلك أدخل كلمة المرور',
  'PasswordPattern': 'يجب أن تكون كلمة المرور على الأقل من 6 إلى 12 حرفاً ، وتشمل أحرف كبيرة ، صغيرة ، أرقام ، و حروف خاصة',
  'ConfirmPassword': 'تأكيد كلمة المرور',
  'ConfirmPasswordReq': 'من فضلك أدخل كلمة المرور',
  'ConfirmPasswordNotMatch': 'كلمة المرور و تاكيد كلمة المرور غير متطابقتين',
  'Attachments': 'المستندات',
  // page plan details 
  'PlanName': 'أسم الخطة',
  'Description': '   وصف الخطة',
  'MaxTripTime': 'مدي الرحلة الكلي(بالدقائق) ',
  'WaitingTime': 'مدة الانتظار(بالدقائق) ',
  'Type': 'نوع الخطة',
  'StartTime': 'وقت بداية الرحلة',
  'EndTime': 'وقت نهاية الرحلة',
  'StartDate': 'مدة التنفيذ (من)',
  'EndDate': 'مدة التنفيذ (إلي)',
  'Days': 'أيام الأسبوع',
  'BasicDetails': 'بيانات الخطة الأساسية',
  'PlanExecutionRange': 'مدة تنفيذ الخطة',
  'WaitingTimeMustByMoreThanZero': 'يجب أن يكون وقت الانتظار أكبر من صفر',
  'MaxTripTimeMustByMoreThanZero': 'يجب أن يكون مدي الرحلة الكلي أكبر من صفر',
  'AtLeastOneDayRequired': 'من فضلك قم بأختيار و تفعيل يوم علي الاقل لاعادة تنفيذ الرحلات بالخطة',
  'status': 'حالة الرحلة',
  'NotStarted': 'لم تبدأ',
  'InProgress': 'قيد التنفيذ',

  // page plan  students buses
  'Branch': 'الفرع الرئيسي',
  'SubBranch': 'الفرع الثانوي',
  'StudentName': 'أسم الطالب',
  'Search': 'بحث',
  'Busses': 'الحافلات',
  'StudentSelected': ' طالب ',
  'students': 'الطلاب',
  'Selected': 'تم إختيار ',
  'GenerateTrips': 'أنشاء الرحلات',
  'Back': 'السابق',
  'useanunifed': 'أستخدام نقطة البداية و الوصول لجميع الحافلات',
  'occurance': 'أيام الأسبوع',
  'plannedstudent': 'طلاب مقيديين بالرحلات',
  'plateNo': 'رقم لوحة الحافلة',
  'TotalMielage': 'المسافة ',
  'Duration': 'مدة الرحلة',
  'SelectName': 'أختر اسم أو كود الخطة ',
  'Update': 'تعديل',
  'code': 'كود الخطة',
  'Planed': 'Planned',
  'PlanedTime': 'وقت الرحلة المجدول',
  'Actuals': 'وقت الرحلة الحقيقي',
  'Play': 'تشغيل',
  'tripmonitoring': 'تفاصيل الرحلة',

  // plan list 
  'PlanCode': 'كود الخطة',
  'NewPlan': 'أضافة خطة جديدة ',
  'PlanType': 'نوع الخطة',
  'Trips': 'الرحلات',
  'SelectPlan': 'أختر اسم الخطة ',
  'SelectPlanType ': 'أختر نوع الخطة',
  'SelectPlanCode': 'أختر كود الخطة ',
  'PlanList': ' قائمة الخطط',
  'TripsList': 'قائمة الرحلات',
  'PikeDate': 'أختر تاريخ',
  'BusCode': 'كود الحافلة',
  'PlateNumber': 'رقم لوحة الحافلة',
  'DriverName': 'السائق',
  'SupervisorName': 'مشرف الرحلة',
  'SelectSupervisor': 'أختر اسم او كود المشرف ',
  'SelectDriver': 'اختر اسم او كود السائق ',
  'PlannedTime': 'وقت الرحلة المجدول',
  'ActualTime': 'وقت الرحلة الحقيقي',
  'PlannedStudents': 'الطلاب المقيدين',
  'ActualStudents': 'الحضور',
  'Status': 'حالة الرحلة',
  'TripStatus': 'حالة الرحلة',
  'NoTripsShow': 'لا يوجد رحلات مجدولة',
  'tripdetails': 'تفاصيل الرحلة',
  'showtrips': 'عرض الرحلات اليومية',
  'ActiveInactive ': 'Active/ Inactive ',
  'Name': ' اسم الخطة',
  'From': 'من',
  'Reset': 'أعادة ضبط',
  'itemsin': 'عناصر',
  'page': 'صفحة',
  'Plannedfrom': 'وقت الرحلة المجدول (من)',
  'Plannedto': 'وقت الرحلة المجدول (إلي)',
  'Actualfrom': 'وقت الرحلة الحقيقي (من)',
  'Actualto': 'وقت الرحلة الحقيقي (إلي)',
  'VehicleCodePlateNumber': 'الحافلة',

  'ArrivalTime': 'وقت الوصول',
  'Planning': 'التخطيط',
  'messagevalidationplandate': 'يجب أن يكون تاريخ البدء قبل تاريخ انتهاء الرحلة',
  'messagevalidationplantime': 'يجب أن يكون وقت الوصول بعد وقت بدء الرحلة ',
  // page plan details 

  'tripstatus': 'حالة الرحلة',
  'planned trip id': 'رقم الرحلة المخططة',
  'EnterDetails': 'بيانات الخطة',
  'StudentAndBus': 'الطلاب و الحافلات',
  'generatedtrips': 'أنشاء الرحلات',

  'Crew': 'طاقم العمل',
  'SupervisourName': 'اسم مشرف الرحلة',
  'AssignedCrew': 'طاقم العمل',
  'AssignedVeicle': 'الحافلة',
  'BusNumberPlate': 'رقم لوحة حافلة ',
  'SelectBus': 'أختر رقم لوحة حافلة بديل',
  'SelectBusTripDetails': ' أختر رقم لوحة الحافلة  ',

  'PlanDate': 'التاربخ الخطة',
  'PlanTime': 'وقت الخطة',
  'PlanMielage': 'المسافة',
  'PlanStudents': 'الطلاب المقيديين ',
  'Pickup': 'نقطة الالتقاط',
  'Dropoff': 'نقطة الانزال',
  'PlanTripDuration': 'مدة الرحلة المجدولة',
  'ActualDate': 'تاريخ التنفيذ',
  'PickupLocation': 'نقطة الالتقاط',
  'DropOffLocation': 'نقطة الانزال',

  'ActualMielage': 'المسافة المقطوعة',
  'ActualTripDuration': 'مدة الرحلة الحقيقية',
  'BusNo': 'رقم الحافلة',
  'MissedBuss': 'لم يحضر',
  'inBus': 'علي متن الحافلة',
  'WaitintgPickUp': 'منتظر',
  'Absent': 'غائب',
  'Active': 'Active',
  'pause': 'متوقف',
  'replay': 'أعادة تشغيل',
  'missed': 'لم يحضر',
  'absent': 'غائب',
  'onboard': 'علي متن الحافلة',
  'Delete': 'ألغاء',
  'Dropped': 'نزل',
  'Completed': 'تمت',
  'Failed': 'فشلت',
  'Cancelled': 'ألغيت',
  'hold': 'قيد الانتظار',
  'GeneralError': 'حدث خطأ غير متوقع,من فضلك اعد المحاولة بعد قليل.اذا استمرت المشكلة من فضلك قم بالاتصال بمدير النظام',
  'EmailExist': 'البريد الألكتروني تم حفظه سابقاً لبيانات ولي أمرآخر ,من فضلك ادخل بريد ألكتروني آخر ',
  'UserNameExist': ' أسم المستخدم تم حفظه سابقاً لبيانات ولي أمرآخر ,من فضلك ادخل أسم مستخدم آخر',
  'IdExist': 'رقم هوية ولي الأمر تم حفظه سابقاً ',
  'getProfile': 'عرض بيانات ولي الأمر',
  'GuardSaved': 'تم حفظ بيانات ولي الأمر بنجاح',
  'GuardRemoveConstrain': ' للاسف لا يمكن حذف بيانات ولي الأمر نهائياً من النظام لانه مرتبط بطلاب آخرين، لأتمام عملية الحذف يمكنك أولاً حذف علاقة ولي الأمر بجميع الطلاب  المعيين عليهم ',
  'OR': 'أو',
  //menu
  'Resources': 'أدارة الموارد',
  'Operations': 'أدارة العمليات',
  'Maintenance': 'أدارة الصيانة',
  'GPS': 'أدارة تتبع المركبات',
  'RentCars': 'أدارة تأجير المركبات',
  'ManageSchool': 'أدارة الحافلات الذكية',
  'Reports': 'التقارير',

  // Shools Tab 
  'Sco_PlansManage': 'التخطيط',
  'Sco_StudentsManage': 'الطلاب و أولياء الامور',
  'Sco_TripsManage': 'الرحلات',
  // Rent Cars 
  'Rent_Dashboard': 'لوحة تقارير تأجير المركبات ',
  'Rent_PricePlans': 'خطط أسعار تأجير المركبات',
  'Rent_AssignPrice': 'ربط المركبات بخطط الأسعار ',
  'Rent_Promotion': 'الخطط الترويجية',
  'Rent_AdditionalServices': 'الخدمات الإضافية',
  'Rent_Customers': 'العملاء',
  'Rent_RentVehicle': 'تأجير المركبات',
  'Rent_ReturnVehicle': 'إرجاع المركبات',
  'Rent_RentContracts': ' عقود الإيجار',

  // Reports tab 
  'rep_General': 'التقارير العامة',
  'rep_GPS': '  تقارير التتبع و تحديد المواقع ',
  'rep_Maintenance': 'تقارير الصيانة',
  'rep_Operations': 'تقارير التشغيل',
  'rep_RentCars': 'تقارير تأجير المركبات',

  // Gps
  'Gps_LiveTracking': 'التتبع المباشر',
  'Gps_FleetMonitoring': 'تتبع و مراقبة المركبات',
  'Gps_Geofences': 'الحدود الجغرافية',
  'Gps_Group': 'المجموعات',

  //Operations
  'oper_Landmarks': 'نقاط التمركز',
  'oper_Routes': 'خطوط السير',
  'oper_WorkOrders': 'أوامر التشغيل',
  'oper_Monitor': 'متابعة أوامر التشغيل',

  // Resources 
  'Res_Dashboard': 'لوحة تقاريرالموارد',
  'Res_Vehicles': 'المركبات',
  'Res_Staff': 'طاقم العمل',
  'Res_Structure': 'الهيكل والتوزيع',

  // Maintenance
  'maint_RFR': 'طلبات الصيانة',
  'maint_Accident': 'طلبات بلاغات الحوادث',
  'maint_PM_RFR': 'طلبات الصيانة الدورية',
  'maint_CM_RFR': 'طلبات صيانة الأعطال الطارئة',
  'maint_WorkOrder': 'أوامر الصيانة',
  'maint_Vendor': 'أوامر الصيانة بمركز الصيانة',
  'maint_Preventive': 'الصيانة الدورية المستحقة',
  'maint_Dashboard': 'لوحة تقارير الصيانة',

  // Student List 
  'StudentList': 'قائمة الطلاب',
  'Allocation': 'الفرع',
  'EmergencyContact': 'قائمة الاتصال في حالات الطوارئ',
  'NA': ' لا يوجد',
  'NoResultisfound': 'لا توجد نتائج',
  'Guardians': 'أسم ولي الأمر',
  'StdType': 'نوع الرحلة',
  'Grade': 'الصف الدراسي',
  'Classes': 'الفصل الدراسي',
  'Gender': 'النوع',
  'RFID': 'الرقم التعريفي',
  'BusSubscription': 'أشتراك الحافلة',
  'StudentEmail': 'البريد الالكتروني',
  'StudentMobile': 'الهاتف المحمول',
  'AdvancedSearch': 'بحث متقدم',
  'StudentDetails': 'بيانات الطالب',
  'AddNewStudent': 'إضافه طالب',
  'SelectBranchName': ' أختر اسم الفرع الرئيسي ',
  'SelectSubBranchName': 'أختر اسم الفرع الثانوي ',
  // student data

  'Upload': 'تحميل',
  'GradeAndClass': 'الصف و الفصل الدراسي',
  'DateOfBirth': 'تاريخ الميلاد',
  'latitude': 'خط العرض',
  'longitude': 'خط الطول',

  'NoSubscription': 'غير مشترك بالحافلة',
  'StudentEmailID': 'البريد الألكتروني',
  'NotValid': 'not valid',
  'PersonalIdentification': '(RFID)الرقم التعريفي',
  'DownloadSample': 'تحميل نموزج',
  'Browse': 'اعرض',
  'guardianBulkUpload': 'إضافة متعددة',
  'StudentBulkUpload': 'إضافة متعددة',
  // generate plan 
  'StartLocation': 'نقطة البداية',
  'EndLocation': 'نقطة النهاية',
  'StartAt': 'وقت بداية الرحلة',
  'EndAt': 'وقت نهاية الرحلة',
  'SeatsReserved': 'عدد المقاعد المحجوزة',


  'SearchStudentName': "أختر اسم الطالب",
  'SelectAll': 'حدد الكل',
  'UnSelectAll': 'إلغاء تحديد الكل',
  'SelectClass': 'أختر الصف الدراسي',
  'SelectGender': 'أخترجنس الطالب',
  'SelectBranch': ' أختر اسم الفرع الرئيسي',
  'SelectSubBranch': 'أختر أسم الفرع الثانوي',
  'SelectRFID': "أختر الرقم التعريفي ",
  'SelectSubscription': "أختر حالة الاشتراك بالحافلة",
  'SelectEmail': "أختر البريد الألكتروني",
  'SelectMobile': "أختررقم الهاتف المحمول",
  'SelectGrade': "أختر الصف الدراسي",
  'SelectPlanType': "أختر نوع الخطة",
  'SelectCode': "أختر كود الطالب",
  'SelectGuardians': "أختر اسم ولي الأمر ",
  'EnterStudentEmail': "أدخل البريد الألكتروني",
  'EnterStudentMobile': "أدخل رقم الهاتف المحمول ",

  'PleaseSelectSubBranch': 'أختر اسم الفرع الثانوي',
  'PleaseSelectBranch': 'أختر اسم الفرع الرئيسي',
  'SelectDateOfBirth': 'أختر تاريخ الميلاد',
  'EnterCode': "أدخل كود",
  'EnterStudentCode': "أدخل كود",
  'ReenterPassword': 'أعد كتابة كلمة المرور ',

  //Dashboard
  'Dashboard': 'Trip List > Live Trip Monitoring',
  'vehicle': 'الحافلة',
  'VehivleSearch': 'أختر كود او رقم لوحة الحافلة',
  'DestLandMark': 'نقطة النهاية',
  'StartLandMark': 'نقطة البداية',
  'PlannedStartTime': 'وقت بداية الرحلة المجدول',
  'PlannedEndTime': 'وقت نهاية الرحلة المجدول',
  'ActuallStartTime': 'وقت بداية الرحلة الحقيقي',
  'ActuallEndTime': 'وقت نهاية الرحلة الحقيقي',
  'Time': 'وقت',
  'Plan': 'الخطة',
  'Actual': 'الحقيقي',
  'Route': 'Route',
  'Outside': 'بالخارج',
  'Onboard': 'Onboard',
  'AllCategories': 'جميع الفئات',
  'GPS_DashboardKey' : 'لوحة تقارير تتبع المركبات',

  //Permit
  'Permits':'تصاريح الناقلات',
  
  'TMS_zonelist':'Zone List',
  'TMS_orderlist':'Order List',
  'TMS_entrygate':'Order List',
  'TMS_exitgate':'Order List',
  'TMS':'Tankers Management System'
};
