//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.CustomerSMS.WinService.SMSServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ws.linq2.is.com/", ConfigurationName="SMSServiceRef.SmsWebService")]
    public interface SmsWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="XmlResponse")]
        NWC.CustomerSMS.WinService.SMSServiceRef.xmlWsResponse send(NWC.CustomerSMS.WinService.SMSServiceRef.eaiMessage EAIMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="XmlResponse")]
        System.Threading.Tasks.Task<NWC.CustomerSMS.WinService.SMSServiceRef.xmlWsResponse> sendAsync(NWC.CustomerSMS.WinService.SMSServiceRef.eaiMessage EAIMessage);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.linq2.is.com/")]
    public partial class eaiMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string evnt_IdField;
        
        private string evnt_SourceField;
        
        private string evnt_PriorityField;
        
        private string org_IdField;
        
        private string due_DtField;
        
        private string validityField;
        
        private int sMS_TypeField;
        
        private string sMSField;
        
        private string sMSSenderField;
        
        private int email_TypeField;
        
        private string emailField;
        
        private string fax_InvitationField;
        
        private string fax_FileField;
        
        private rcpntDtls[] rcpnt_LstField;
        
        public eaiMessage() {
            this.evnt_PriorityField = "1";
            this.org_IdField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Evnt_Id {
            get {
                return this.evnt_IdField;
            }
            set {
                this.evnt_IdField = value;
                this.RaisePropertyChanged("Evnt_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Evnt_Source {
            get {
                return this.evnt_SourceField;
            }
            set {
                this.evnt_SourceField = value;
                this.RaisePropertyChanged("Evnt_Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string Evnt_Priority {
            get {
                return this.evnt_PriorityField;
            }
            set {
                this.evnt_PriorityField = value;
                this.RaisePropertyChanged("Evnt_Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
                this.RaisePropertyChanged("Org_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Due_Dt {
            get {
                return this.due_DtField;
            }
            set {
                this.due_DtField = value;
                this.RaisePropertyChanged("Due_Dt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string Validity {
            get {
                return this.validityField;
            }
            set {
                this.validityField = value;
                this.RaisePropertyChanged("Validity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int SMS_Type {
            get {
                return this.sMS_TypeField;
            }
            set {
                this.sMS_TypeField = value;
                this.RaisePropertyChanged("SMS_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SMS {
            get {
                return this.sMSField;
            }
            set {
                this.sMSField = value;
                this.RaisePropertyChanged("SMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SMSSender {
            get {
                return this.sMSSenderField;
            }
            set {
                this.sMSSenderField = value;
                this.RaisePropertyChanged("SMSSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int Email_Type {
            get {
                return this.email_TypeField;
            }
            set {
                this.email_TypeField = value;
                this.RaisePropertyChanged("Email_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Fax_Invitation {
            get {
                return this.fax_InvitationField;
            }
            set {
                this.fax_InvitationField = value;
                this.RaisePropertyChanged("Fax_Invitation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Fax_File {
            get {
                return this.fax_FileField;
            }
            set {
                this.fax_FileField = value;
                this.RaisePropertyChanged("Fax_File");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Rcpnt_Dtls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public rcpntDtls[] Rcpnt_Lst {
            get {
                return this.rcpnt_LstField;
            }
            set {
                this.rcpnt_LstField = value;
                this.RaisePropertyChanged("Rcpnt_Lst");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.linq2.is.com/")]
    public partial class rcpntDtls : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ntfctn_MthdField;
        
        private string ntfctn_LngField;
        
        private string ntfctn_EncField;
        
        private string provider_IdField;
        
        private string group_IdField;
        
        private string contact_IdField;
        
        private string fax_NumberField;
        
        private string mbl_TelField;
        
        private string dlv_NtfnField;
        
        private string email_ToField;
        
        private string email_CCField;
        
        private string email_BCCField;
        
        private string email_serverField;
        
        private string email_SbjctField;
        
        private string att_Fl_NameField;
        
        private string att_Dp_NameField;
        
        private string additional_infoField;
        
        private paramerter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Ntfctn_Mthd {
            get {
                return this.ntfctn_MthdField;
            }
            set {
                this.ntfctn_MthdField = value;
                this.RaisePropertyChanged("Ntfctn_Mthd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Ntfctn_Lng {
            get {
                return this.ntfctn_LngField;
            }
            set {
                this.ntfctn_LngField = value;
                this.RaisePropertyChanged("Ntfctn_Lng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ntfctn_Enc {
            get {
                return this.ntfctn_EncField;
            }
            set {
                this.ntfctn_EncField = value;
                this.RaisePropertyChanged("Ntfctn_Enc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Provider_Id {
            get {
                return this.provider_IdField;
            }
            set {
                this.provider_IdField = value;
                this.RaisePropertyChanged("Provider_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Group_Id {
            get {
                return this.group_IdField;
            }
            set {
                this.group_IdField = value;
                this.RaisePropertyChanged("Group_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Contact_Id {
            get {
                return this.contact_IdField;
            }
            set {
                this.contact_IdField = value;
                this.RaisePropertyChanged("Contact_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Fax_Number {
            get {
                return this.fax_NumberField;
            }
            set {
                this.fax_NumberField = value;
                this.RaisePropertyChanged("Fax_Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Mbl_Tel {
            get {
                return this.mbl_TelField;
            }
            set {
                this.mbl_TelField = value;
                this.RaisePropertyChanged("Mbl_Tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Dlv_Ntfn {
            get {
                return this.dlv_NtfnField;
            }
            set {
                this.dlv_NtfnField = value;
                this.RaisePropertyChanged("Dlv_Ntfn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Email_To {
            get {
                return this.email_ToField;
            }
            set {
                this.email_ToField = value;
                this.RaisePropertyChanged("Email_To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Email_CC {
            get {
                return this.email_CCField;
            }
            set {
                this.email_CCField = value;
                this.RaisePropertyChanged("Email_CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Email_BCC {
            get {
                return this.email_BCCField;
            }
            set {
                this.email_BCCField = value;
                this.RaisePropertyChanged("Email_BCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Email_server {
            get {
                return this.email_serverField;
            }
            set {
                this.email_serverField = value;
                this.RaisePropertyChanged("Email_server");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Email_Sbjct {
            get {
                return this.email_SbjctField;
            }
            set {
                this.email_SbjctField = value;
                this.RaisePropertyChanged("Email_Sbjct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Att_Fl_Name {
            get {
                return this.att_Fl_NameField;
            }
            set {
                this.att_Fl_NameField = value;
                this.RaisePropertyChanged("Att_Fl_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Att_Dp_Name {
            get {
                return this.att_Dp_NameField;
            }
            set {
                this.att_Dp_NameField = value;
                this.RaisePropertyChanged("Att_Dp_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Additional_info {
            get {
                return this.additional_infoField;
            }
            set {
                this.additional_infoField = value;
                this.RaisePropertyChanged("Additional_info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public paramerter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.linq2.is.com/")]
    public partial class paramerter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paramnameField;
        
        private string paramvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param-name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paramname {
            get {
                return this.paramnameField;
            }
            set {
                this.paramnameField = value;
                this.RaisePropertyChanged("paramname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param-value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string paramvalue {
            get {
                return this.paramvalueField;
            }
            set {
                this.paramvalueField = value;
                this.RaisePropertyChanged("paramvalue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ws.linq2.is.com/")]
    public partial class xmlWsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string evnt_IdField;
        
        private string statusField;
        
        private string error_CodeField;
        
        private string error_DescriptionField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Evnt_Id {
            get {
                return this.evnt_IdField;
            }
            set {
                this.evnt_IdField = value;
                this.RaisePropertyChanged("Evnt_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
                this.RaisePropertyChanged("Error_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Error_Description {
            get {
                return this.error_DescriptionField;
            }
            set {
                this.error_DescriptionField = value;
                this.RaisePropertyChanged("Error_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsWebServiceChannel : NWC.CustomerSMS.WinService.SMSServiceRef.SmsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsWebServiceClient : System.ServiceModel.ClientBase<NWC.CustomerSMS.WinService.SMSServiceRef.SmsWebService>, NWC.CustomerSMS.WinService.SMSServiceRef.SmsWebService {
        
        public SmsWebServiceClient() {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NWC.CustomerSMS.WinService.SMSServiceRef.xmlWsResponse send(NWC.CustomerSMS.WinService.SMSServiceRef.eaiMessage EAIMessage) {
            return base.Channel.send(EAIMessage);
        }
        
        public System.Threading.Tasks.Task<NWC.CustomerSMS.WinService.SMSServiceRef.xmlWsResponse> sendAsync(NWC.CustomerSMS.WinService.SMSServiceRef.eaiMessage EAIMessage) {
            return base.Channel.sendAsync(EAIMessage);
        }
    }
}
