//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotificationProject/TMSNwcUpdateWONotificatio" +
        "n", ConfigurationName="UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt")]
    public interface TMSNwcUpdateWONotification_ptt {
        
        // CODEGEN: Generating message contract since the operation updateWorkOrserStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="updateWorkOrserStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse updateWorkOrserStatus(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="updateWorkOrserStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse> updateWorkOrserStatusAsync(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification")]
    public partial class TMSWONotificationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private TMSWONotificationRequestSourceApplication sourceApplicationField;
        
        private string orderNumberField;
        
        private cisDivison cisDivisionField;
        
        private TMSWONotificationRequestOrderStatus orderStatusField;
        
        private string updateDateTimeField;
        
        private TMSWONotificationRequestParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TMSWONotificationRequestSourceApplication sourceApplication {
            get {
                return this.sourceApplicationField;
            }
            set {
                this.sourceApplicationField = value;
                this.RaisePropertyChanged("sourceApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("orderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public cisDivison cisDivision {
            get {
                return this.cisDivisionField;
            }
            set {
                this.cisDivisionField = value;
                this.RaisePropertyChanged("cisDivision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TMSWONotificationRequestOrderStatus orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string updateDateTime {
            get {
                return this.updateDateTimeField;
            }
            set {
                this.updateDateTimeField = value;
                this.RaisePropertyChanged("updateDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public TMSWONotificationRequestParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification")]
    public enum TMSWONotificationRequestSourceApplication {
        
        /// <remarks/>
        TMS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eChannelService.nwc.com.sa")]
    public enum cisDivison {
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        RCBU,
        
        /// <remarks/>
        JCBU,
        
        /// <remarks/>
        TCBU,
        
        /// <remarks/>
        MCBU,
        
        /// <remarks/>
        JZBU,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        RI,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        TB,
        
        /// <remarks/>
        RC,
        
        /// <remarks/>
        JC,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        TC,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        QS,
        
        /// <remarks/>
        HS,
        
        /// <remarks/>
        HA,
        
        /// <remarks/>
        JF,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        NJ,
        
        /// <remarks/>
        JZ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification")]
    public enum TMSWONotificationRequestOrderStatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification")]
    public partial class TMSWONotificationRequestParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parameterNameField;
        
        private string parameterValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string parameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
                this.RaisePropertyChanged("parameterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string parameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
                this.RaisePropertyChanged("parameterValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification")]
    public partial class TMSWONotificationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string sourceApplicationField;
        
        private string statusField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceApplication {
            get {
                return this.sourceApplicationField;
            }
            set {
                this.sourceApplicationField = value;
                this.RaisePropertyChanged("sourceApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkOrserStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification", Order=0)]
        public NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationRequest TMSWONotificationRequest;
        
        public updateWorkOrserStatusRequest() {
        }
        
        public updateWorkOrserStatusRequest(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationRequest TMSWONotificationRequest) {
            this.TMSWONotificationRequest = TMSWONotificationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkOrserStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.nwc.com.sa/TMSNwcUpdateWONotification", Order=0)]
        public NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationResponse TMSWONotificationResponse;
        
        public updateWorkOrserStatusResponse() {
        }
        
        public updateWorkOrserStatusResponse(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationResponse TMSWONotificationResponse) {
            this.TMSWONotificationResponse = TMSWONotificationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TMSNwcUpdateWONotification_pttChannel : NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSNwcUpdateWONotification_pttClient : System.ServiceModel.ClientBase<NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt>, NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt {
        
        public TMSNwcUpdateWONotification_pttClient() {
        }
        
        public TMSNwcUpdateWONotification_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMSNwcUpdateWONotification_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSNwcUpdateWONotification_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSNwcUpdateWONotification_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt.updateWorkOrserStatus(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest request) {
            return base.Channel.updateWorkOrserStatus(request);
        }
        
        public NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationResponse updateWorkOrserStatus(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationRequest TMSWONotificationRequest) {
            NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest inValue = new NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest();
            inValue.TMSWONotificationRequest = TMSWONotificationRequest;
            NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse retVal = ((NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt)(this)).updateWorkOrserStatus(inValue);
            return retVal.TMSWONotificationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse> NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt.updateWorkOrserStatusAsync(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest request) {
            return base.Channel.updateWorkOrserStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusResponse> updateWorkOrserStatusAsync(NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSWONotificationRequest TMSWONotificationRequest) {
            NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest inValue = new NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.updateWorkOrserStatusRequest();
            inValue.TMSWONotificationRequest = TMSWONotificationRequest;
            return ((NWC_CCB_Integration.BLL.UpdateWONotificationServiceRef.TMSNwcUpdateWONotification_ptt)(this)).updateWorkOrserStatusAsync(inValue);
        }
    }
}
