//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.Integration.WinService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NWCResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NWCResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NWC.Integration.WinService.Properties.NWCResources", typeof(NWCResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Customer Location.
        /// </summary>
        public static string ChooseCustomerLocation {
            get {
                return ResourceManager.GetString("ChooseCustomerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Service Type.
        /// </summary>
        public static string ChooseServiceType {
            get {
                return ResourceManager.GetString("ChooseServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Station.
        /// </summary>
        public static string ChooseStation {
            get {
                return ResourceManager.GetString("ChooseStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Station Does Not Has Accessories.
        /// </summary>
        public static string ContractStationDoesNotHasAccessories {
            get {
                return ResourceManager.GetString("ContractStationDoesNotHasAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tariff Defined in TMS.
        /// </summary>
        public static string ContractStationDoesNotHasTariff {
            get {
                return ResourceManager.GetString("ContractStationDoesNotHasTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Location Does Not Exist.
        /// </summary>
        public static string CustomerLocationDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerLocationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contract.
        /// </summary>
        public static string InvalidContract {
            get {
                return ResourceManager.GetString("InvalidContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Quantity.
        /// </summary>
        public static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number Already Exist.
        /// </summary>
        public static string OrderNumberAlreadyExist {
            get {
                return ResourceManager.GetString("OrderNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Does Not Assigned To Contract.
        /// </summary>
        public static string StationDoesNotAssignedToContract {
            get {
                return ResourceManager.GetString("StationDoesNotAssignedToContract", resourceCulture);
            }
        }
    }
}
