//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NWC_CCBEntities : DbContext
    {
        public NWC_CCBEntities()
            : base("name=NWC_CCBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NWC_Int_ObjectLog> NWC_Int_ObjectLog { get; set; }
        public virtual DbSet<NWC_Int_ObjectLogDTO> NWC_Int_ObjectLogDTO { get; set; }
        public virtual DbSet<NWC_DefaultTankerSize> NWC_DefaultTankerSize { get; set; }
        public virtual DbSet<NWC_DeferredWorkOrderStatus> NWC_DeferredWorkOrderStatus { get; set; }
        public virtual DbSet<NWC_DeferredWorkOrder> NWC_DeferredWorkOrder { get; set; }
        public virtual DbSet<NWC_Int_ObjectStatus> NWC_Int_ObjectStatus { get; set; }
    }
}
