//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Int_ObjectLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NWC_Int_ObjectLog()
        {
            this.NWC_Int_ObjectLogDTO = new HashSet<NWC_Int_ObjectLogDTO>();
        }
    
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> OperationTypeID { get; set; }
        public Nullable<int> OperationStepID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NWC_Int_ObjectLogDTO> NWC_Int_ObjectLogDTO { get; set; }
    }
}
