//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Int_ObjectStatus
    {
        public long ID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public Nullable<int> OperationTypeID { get; set; }
        public string DTO { get; set; }
        public string XML { get; set; }
        public string Token { get; set; }
        public int Retrials { get; set; }
        public string FailureMessage { get; set; }
    }
}
