//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_DeferredWorkOrder
    {
        public long ID { get; set; }
        public string ORDERNUMBER { get; set; }
        public string CISDIVISION { get; set; }
        public string COMMENT { get; set; }
        public string CONFIRMATIONCODE { get; set; }
        public string CONTACTMOBILE { get; set; }
        public string CONTACTNAME { get; set; }
        public string CREDTTM { get; set; }
        public string SCHEDDTTM { get; set; }
        public string SERVICETYPE { get; set; }
        public string SOURCEAPPLICATION { get; set; }
        public string TANKERSIZE { get; set; }
        public string TRANSACTIONID { get; set; }
        public string ACCOUNTID { get; set; }
        public string CUSTOMERCLASS { get; set; }
        public string MOBILENUMBER { get; set; }
        public string PERSONID { get; set; }
        public string PERSONIDTYPE { get; set; }
        public string PERSONIDVALUE { get; set; }
        public string PERSONPRIMARYNAME { get; set; }
        public string PREMISEID { get; set; }
        public string XYCOORDINATESGF { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ErrorMSG { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual NWC_DeferredWorkOrderStatus NWC_DeferredWorkOrderStatus { get; set; }
    }
}
