//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC_CCB_Integration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWC_Int_ObjectLogDTO
    {
        public long ID { get; set; }
        public long LogID { get; set; }
        public string DTO { get; set; }
    
        public virtual NWC_Int_ObjectLog NWC_Int_ObjectLog { get; set; }
    }
}
