//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWC.BLL.GISServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/eChannelApplication/echannelGetLocationInfoProject/echann" +
        "elGetLocationInfo", ConfigurationName="GISServiceRef.echannelGetLocationInfoPortType")]
    public interface echannelGetLocationInfoPortType {
        
        // CODEGEN: Generating message contract since the operation echannelGetLocationInfoOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="echannelGetLocationInfoOperation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse echannelGetLocationInfoOperation(NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="echannelGetLocationInfoOperation", ReplyAction="*")]
        System.Threading.Tasks.Task<NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse> echannelGetLocationInfoOperationAsync(NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.echannelGetLocationInfoProject.org")]
    public partial class echannelGetLocationInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private echannelGetLocationInfoRequestSourceApplication sourceApplicationField;
        
        private string orgCodeField;
        
        private string locTypeField;
        
        private string locValueField;
        
        private string outputinfoTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public echannelGetLocationInfoRequestSourceApplication sourceApplication {
            get {
                return this.sourceApplicationField;
            }
            set {
                this.sourceApplicationField = value;
                this.RaisePropertyChanged("sourceApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orgCode {
            get {
                return this.orgCodeField;
            }
            set {
                this.orgCodeField = value;
                this.RaisePropertyChanged("orgCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locType {
            get {
                return this.locTypeField;
            }
            set {
                this.locTypeField = value;
                this.RaisePropertyChanged("locType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string locValue {
            get {
                return this.locValueField;
            }
            set {
                this.locValueField = value;
                this.RaisePropertyChanged("locValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string outputinfoType {
            get {
                return this.outputinfoTypeField;
            }
            set {
                this.outputinfoTypeField = value;
                this.RaisePropertyChanged("outputinfoType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.echannelGetLocationInfoProject.org")]
    public enum echannelGetLocationInfoRequestSourceApplication {
        
        /// <remarks/>
        EBRANCH,
        
        /// <remarks/>
        MOBAPP,
        
        /// <remarks/>
        CCB,
        
        /// <remarks/>
        TMS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.echannelGetLocationInfoProject.org")]
    public partial class echannelGetLocationInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string sourceApplicationField;
        
        private string outputTypeField;
        
        private string outputValueField;
        
        private string statusField;
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sourceApplication {
            get {
                return this.sourceApplicationField;
            }
            set {
                this.sourceApplicationField = value;
                this.RaisePropertyChanged("sourceApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string outputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
                this.RaisePropertyChanged("outputType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string outputValue {
            get {
                return this.outputValueField;
            }
            set {
                this.outputValueField = value;
                this.RaisePropertyChanged("outputValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echannelGetLocationInfoOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.echannelGetLocationInfoProject.org", Order=0)]
        public NWC.BLL.GISServiceRef.echannelGetLocationInfoRequest echannelGetLocationInfoRequest;
        
        public echannelGetLocationInfoOperationRequest() {
        }
        
        public echannelGetLocationInfoOperationRequest(NWC.BLL.GISServiceRef.echannelGetLocationInfoRequest echannelGetLocationInfoRequest) {
            this.echannelGetLocationInfoRequest = echannelGetLocationInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echannelGetLocationInfoOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.echannelGetLocationInfoProject.org", Order=0)]
        public NWC.BLL.GISServiceRef.echannelGetLocationInfoResponse echannelGetLocationInfoResponse;
        
        public echannelGetLocationInfoOperationResponse() {
        }
        
        public echannelGetLocationInfoOperationResponse(NWC.BLL.GISServiceRef.echannelGetLocationInfoResponse echannelGetLocationInfoResponse) {
            this.echannelGetLocationInfoResponse = echannelGetLocationInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface echannelGetLocationInfoPortTypeChannel : NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class echannelGetLocationInfoPortTypeClient : System.ServiceModel.ClientBase<NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType>, NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType {
        
        public echannelGetLocationInfoPortTypeClient() {
        }
        
        public echannelGetLocationInfoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public echannelGetLocationInfoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echannelGetLocationInfoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echannelGetLocationInfoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType.echannelGetLocationInfoOperation(NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest request) {
            return base.Channel.echannelGetLocationInfoOperation(request);
        }
        
        public NWC.BLL.GISServiceRef.echannelGetLocationInfoResponse echannelGetLocationInfoOperation(NWC.BLL.GISServiceRef.echannelGetLocationInfoRequest echannelGetLocationInfoRequest) {
            NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest inValue = new NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest();
            inValue.echannelGetLocationInfoRequest = echannelGetLocationInfoRequest;
            NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse retVal = ((NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType)(this)).echannelGetLocationInfoOperation(inValue);
            return retVal.echannelGetLocationInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse> NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType.echannelGetLocationInfoOperationAsync(NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest request) {
            return base.Channel.echannelGetLocationInfoOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationResponse> echannelGetLocationInfoOperationAsync(NWC.BLL.GISServiceRef.echannelGetLocationInfoRequest echannelGetLocationInfoRequest) {
            NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest inValue = new NWC.BLL.GISServiceRef.echannelGetLocationInfoOperationRequest();
            inValue.echannelGetLocationInfoRequest = echannelGetLocationInfoRequest;
            return ((NWC.BLL.GISServiceRef.echannelGetLocationInfoPortType)(this)).echannelGetLocationInfoOperationAsync(inValue);
        }
    }
}
